// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bot_import.proto

package com.treeleaf.anydone.entities;

public final class BotImportProto {
  private BotImportProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface BotImportRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:treeleaf.anydone.entities.BotImportRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string url = 1;</code>
     */
    java.lang.String getUrl();
    /**
     * <code>optional string url = 1;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <code>optional string file_name = 2;</code>
     */
    java.lang.String getFileName();
    /**
     * <code>optional string file_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>optional string serviceId = 3;</code>
     */
    java.lang.String getServiceId();
    /**
     * <code>optional string serviceId = 3;</code>
     */
    com.google.protobuf.ByteString
        getServiceIdBytes();

    /**
     * <code>optional string accountId = 4;</code>
     */
    java.lang.String getAccountId();
    /**
     * <code>optional string accountId = 4;</code>
     */
    com.google.protobuf.ByteString
        getAccountIdBytes();

    /**
     * <code>optional string language = 5;</code>
     */
    java.lang.String getLanguage();
    /**
     * <code>optional string language = 5;</code>
     */
    com.google.protobuf.ByteString
        getLanguageBytes();
  }
  /**
   * Protobuf type {@code treeleaf.anydone.entities.BotImportRequest}
   */
  public  static final class BotImportRequest extends
      com.google.protobuf.GeneratedMessageLite<
          BotImportRequest, BotImportRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:treeleaf.anydone.entities.BotImportRequest)
      BotImportRequestOrBuilder {
    private BotImportRequest() {
      url_ = "";
      fileName_ = "";
      serviceId_ = "";
      accountId_ = "";
      language_ = "";
    }
    public static final int URL_FIELD_NUMBER = 1;
    private java.lang.String url_;
    /**
     * <code>optional string url = 1;</code>
     */
    public java.lang.String getUrl() {
      return url_;
    }
    /**
     * <code>optional string url = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(url_);
    }
    /**
     * <code>optional string url = 1;</code>
     */
    private void setUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      url_ = value;
    }
    /**
     * <code>optional string url = 1;</code>
     */
    private void clearUrl() {
      
      url_ = getDefaultInstance().getUrl();
    }
    /**
     * <code>optional string url = 1;</code>
     */
    private void setUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      url_ = value.toStringUtf8();
    }

    public static final int FILE_NAME_FIELD_NUMBER = 2;
    private java.lang.String fileName_;
    /**
     * <code>optional string file_name = 2;</code>
     */
    public java.lang.String getFileName() {
      return fileName_;
    }
    /**
     * <code>optional string file_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(fileName_);
    }
    /**
     * <code>optional string file_name = 2;</code>
     */
    private void setFileName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fileName_ = value;
    }
    /**
     * <code>optional string file_name = 2;</code>
     */
    private void clearFileName() {
      
      fileName_ = getDefaultInstance().getFileName();
    }
    /**
     * <code>optional string file_name = 2;</code>
     */
    private void setFileNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fileName_ = value.toStringUtf8();
    }

    public static final int SERVICEID_FIELD_NUMBER = 3;
    private java.lang.String serviceId_;
    /**
     * <code>optional string serviceId = 3;</code>
     */
    public java.lang.String getServiceId() {
      return serviceId_;
    }
    /**
     * <code>optional string serviceId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getServiceIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(serviceId_);
    }
    /**
     * <code>optional string serviceId = 3;</code>
     */
    private void setServiceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serviceId_ = value;
    }
    /**
     * <code>optional string serviceId = 3;</code>
     */
    private void clearServiceId() {
      
      serviceId_ = getDefaultInstance().getServiceId();
    }
    /**
     * <code>optional string serviceId = 3;</code>
     */
    private void setServiceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serviceId_ = value.toStringUtf8();
    }

    public static final int ACCOUNTID_FIELD_NUMBER = 4;
    private java.lang.String accountId_;
    /**
     * <code>optional string accountId = 4;</code>
     */
    public java.lang.String getAccountId() {
      return accountId_;
    }
    /**
     * <code>optional string accountId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAccountIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(accountId_);
    }
    /**
     * <code>optional string accountId = 4;</code>
     */
    private void setAccountId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accountId_ = value;
    }
    /**
     * <code>optional string accountId = 4;</code>
     */
    private void clearAccountId() {
      
      accountId_ = getDefaultInstance().getAccountId();
    }
    /**
     * <code>optional string accountId = 4;</code>
     */
    private void setAccountIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accountId_ = value.toStringUtf8();
    }

    public static final int LANGUAGE_FIELD_NUMBER = 5;
    private java.lang.String language_;
    /**
     * <code>optional string language = 5;</code>
     */
    public java.lang.String getLanguage() {
      return language_;
    }
    /**
     * <code>optional string language = 5;</code>
     */
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(language_);
    }
    /**
     * <code>optional string language = 5;</code>
     */
    private void setLanguage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      language_ = value;
    }
    /**
     * <code>optional string language = 5;</code>
     */
    private void clearLanguage() {
      
      language_ = getDefaultInstance().getLanguage();
    }
    /**
     * <code>optional string language = 5;</code>
     */
    private void setLanguageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      language_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!url_.isEmpty()) {
        output.writeString(1, getUrl());
      }
      if (!fileName_.isEmpty()) {
        output.writeString(2, getFileName());
      }
      if (!serviceId_.isEmpty()) {
        output.writeString(3, getServiceId());
      }
      if (!accountId_.isEmpty()) {
        output.writeString(4, getAccountId());
      }
      if (!language_.isEmpty()) {
        output.writeString(5, getLanguage());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!url_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getUrl());
      }
      if (!fileName_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getFileName());
      }
      if (!serviceId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getServiceId());
      }
      if (!accountId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getAccountId());
      }
      if (!language_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getLanguage());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.treeleaf.anydone.entities.BotImportProto.BotImportRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.treeleaf.anydone.entities.BotImportProto.BotImportRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.BotImportProto.BotImportRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.treeleaf.anydone.entities.BotImportProto.BotImportRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.BotImportProto.BotImportRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.anydone.entities.BotImportProto.BotImportRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.BotImportProto.BotImportRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.anydone.entities.BotImportProto.BotImportRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.BotImportProto.BotImportRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.anydone.entities.BotImportProto.BotImportRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.treeleaf.anydone.entities.BotImportProto.BotImportRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code treeleaf.anydone.entities.BotImportRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.treeleaf.anydone.entities.BotImportProto.BotImportRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:treeleaf.anydone.entities.BotImportRequest)
        com.treeleaf.anydone.entities.BotImportProto.BotImportRequestOrBuilder {
      // Construct using com.treeleaf.anydone.entities.BotImportProto.BotImportRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string url = 1;</code>
       */
      public java.lang.String getUrl() {
        return instance.getUrl();
      }
      /**
       * <code>optional string url = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        return instance.getUrlBytes();
      }
      /**
       * <code>optional string url = 1;</code>
       */
      public Builder setUrl(
          java.lang.String value) {
        copyOnWrite();
        instance.setUrl(value);
        return this;
      }
      /**
       * <code>optional string url = 1;</code>
       */
      public Builder clearUrl() {
        copyOnWrite();
        instance.clearUrl();
        return this;
      }
      /**
       * <code>optional string url = 1;</code>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUrlBytes(value);
        return this;
      }

      /**
       * <code>optional string file_name = 2;</code>
       */
      public java.lang.String getFileName() {
        return instance.getFileName();
      }
      /**
       * <code>optional string file_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        return instance.getFileNameBytes();
      }
      /**
       * <code>optional string file_name = 2;</code>
       */
      public Builder setFileName(
          java.lang.String value) {
        copyOnWrite();
        instance.setFileName(value);
        return this;
      }
      /**
       * <code>optional string file_name = 2;</code>
       */
      public Builder clearFileName() {
        copyOnWrite();
        instance.clearFileName();
        return this;
      }
      /**
       * <code>optional string file_name = 2;</code>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFileNameBytes(value);
        return this;
      }

      /**
       * <code>optional string serviceId = 3;</code>
       */
      public java.lang.String getServiceId() {
        return instance.getServiceId();
      }
      /**
       * <code>optional string serviceId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getServiceIdBytes() {
        return instance.getServiceIdBytes();
      }
      /**
       * <code>optional string serviceId = 3;</code>
       */
      public Builder setServiceId(
          java.lang.String value) {
        copyOnWrite();
        instance.setServiceId(value);
        return this;
      }
      /**
       * <code>optional string serviceId = 3;</code>
       */
      public Builder clearServiceId() {
        copyOnWrite();
        instance.clearServiceId();
        return this;
      }
      /**
       * <code>optional string serviceId = 3;</code>
       */
      public Builder setServiceIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setServiceIdBytes(value);
        return this;
      }

      /**
       * <code>optional string accountId = 4;</code>
       */
      public java.lang.String getAccountId() {
        return instance.getAccountId();
      }
      /**
       * <code>optional string accountId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAccountIdBytes() {
        return instance.getAccountIdBytes();
      }
      /**
       * <code>optional string accountId = 4;</code>
       */
      public Builder setAccountId(
          java.lang.String value) {
        copyOnWrite();
        instance.setAccountId(value);
        return this;
      }
      /**
       * <code>optional string accountId = 4;</code>
       */
      public Builder clearAccountId() {
        copyOnWrite();
        instance.clearAccountId();
        return this;
      }
      /**
       * <code>optional string accountId = 4;</code>
       */
      public Builder setAccountIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAccountIdBytes(value);
        return this;
      }

      /**
       * <code>optional string language = 5;</code>
       */
      public java.lang.String getLanguage() {
        return instance.getLanguage();
      }
      /**
       * <code>optional string language = 5;</code>
       */
      public com.google.protobuf.ByteString
          getLanguageBytes() {
        return instance.getLanguageBytes();
      }
      /**
       * <code>optional string language = 5;</code>
       */
      public Builder setLanguage(
          java.lang.String value) {
        copyOnWrite();
        instance.setLanguage(value);
        return this;
      }
      /**
       * <code>optional string language = 5;</code>
       */
      public Builder clearLanguage() {
        copyOnWrite();
        instance.clearLanguage();
        return this;
      }
      /**
       * <code>optional string language = 5;</code>
       */
      public Builder setLanguageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLanguageBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:treeleaf.anydone.entities.BotImportRequest)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.treeleaf.anydone.entities.BotImportProto.BotImportRequest();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.treeleaf.anydone.entities.BotImportProto.BotImportRequest other = (com.treeleaf.anydone.entities.BotImportProto.BotImportRequest) arg1;
          url_ = visitor.visitString(!url_.isEmpty(), url_,
              !other.url_.isEmpty(), other.url_);
          fileName_ = visitor.visitString(!fileName_.isEmpty(), fileName_,
              !other.fileName_.isEmpty(), other.fileName_);
          serviceId_ = visitor.visitString(!serviceId_.isEmpty(), serviceId_,
              !other.serviceId_.isEmpty(), other.serviceId_);
          accountId_ = visitor.visitString(!accountId_.isEmpty(), accountId_,
              !other.accountId_.isEmpty(), other.accountId_);
          language_ = visitor.visitString(!language_.isEmpty(), language_,
              !other.language_.isEmpty(), other.language_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  url_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  fileName_ = s;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  serviceId_ = s;
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();

                  accountId_ = s;
                  break;
                }
                case 42: {
                  String s = input.readStringRequireUtf8();

                  language_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.treeleaf.anydone.entities.BotImportProto.BotImportRequest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:treeleaf.anydone.entities.BotImportRequest)
    private static final com.treeleaf.anydone.entities.BotImportProto.BotImportRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BotImportRequest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.treeleaf.anydone.entities.BotImportProto.BotImportRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<BotImportRequest> PARSER;

    public static com.google.protobuf.Parser<BotImportRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
