// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bot_train.proto

package com.treeleaf.anydone.entities;

public final class BotTrainProto {
  private BotTrainProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface BotTrainRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:treeleaf.anydone.entities.BotTrainRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .treeleaf.anydone.entities.TrainRequest trainRequest = 1;</code>
     */
    boolean hasTrainRequest();
    /**
     * <code>optional .treeleaf.anydone.entities.TrainRequest trainRequest = 1;</code>
     */
    com.treeleaf.anydone.entities.BotHousekeepingProto.TrainRequest getTrainRequest();

    /**
     * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
     */
    java.util.List<com.treeleaf.anydone.entities.BotHousekeepingProto.BotEntity> 
        getBotEntitiesList();
    /**
     * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
     */
    com.treeleaf.anydone.entities.BotHousekeepingProto.BotEntity getBotEntities(int index);
    /**
     * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
     */
    int getBotEntitiesCount();
  }
  /**
   * Protobuf type {@code treeleaf.anydone.entities.BotTrainRequest}
   */
  public  static final class BotTrainRequest extends
      com.google.protobuf.GeneratedMessageLite<
          BotTrainRequest, BotTrainRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:treeleaf.anydone.entities.BotTrainRequest)
      BotTrainRequestOrBuilder {
    private BotTrainRequest() {
      botEntities_ = emptyProtobufList();
    }
    private int bitField0_;
    public static final int TRAINREQUEST_FIELD_NUMBER = 1;
    private com.treeleaf.anydone.entities.BotHousekeepingProto.TrainRequest trainRequest_;
    /**
     * <code>optional .treeleaf.anydone.entities.TrainRequest trainRequest = 1;</code>
     */
    public boolean hasTrainRequest() {
      return trainRequest_ != null;
    }
    /**
     * <code>optional .treeleaf.anydone.entities.TrainRequest trainRequest = 1;</code>
     */
    public com.treeleaf.anydone.entities.BotHousekeepingProto.TrainRequest getTrainRequest() {
      return trainRequest_ == null ? com.treeleaf.anydone.entities.BotHousekeepingProto.TrainRequest.getDefaultInstance() : trainRequest_;
    }
    /**
     * <code>optional .treeleaf.anydone.entities.TrainRequest trainRequest = 1;</code>
     */
    private void setTrainRequest(com.treeleaf.anydone.entities.BotHousekeepingProto.TrainRequest value) {
      if (value == null) {
        throw new NullPointerException();
      }
      trainRequest_ = value;
      
      }
    /**
     * <code>optional .treeleaf.anydone.entities.TrainRequest trainRequest = 1;</code>
     */
    private void setTrainRequest(
        com.treeleaf.anydone.entities.BotHousekeepingProto.TrainRequest.Builder builderForValue) {
      trainRequest_ = builderForValue.build();
      
    }
    /**
     * <code>optional .treeleaf.anydone.entities.TrainRequest trainRequest = 1;</code>
     */
    private void mergeTrainRequest(com.treeleaf.anydone.entities.BotHousekeepingProto.TrainRequest value) {
      if (trainRequest_ != null &&
          trainRequest_ != com.treeleaf.anydone.entities.BotHousekeepingProto.TrainRequest.getDefaultInstance()) {
        trainRequest_ =
          com.treeleaf.anydone.entities.BotHousekeepingProto.TrainRequest.newBuilder(trainRequest_).mergeFrom(value).buildPartial();
      } else {
        trainRequest_ = value;
      }
      
    }
    /**
     * <code>optional .treeleaf.anydone.entities.TrainRequest trainRequest = 1;</code>
     */
    private void clearTrainRequest() {  trainRequest_ = null;
      
    }

    public static final int BOTENTITIES_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<com.treeleaf.anydone.entities.BotHousekeepingProto.BotEntity> botEntities_;
    /**
     * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
     */
    public java.util.List<com.treeleaf.anydone.entities.BotHousekeepingProto.BotEntity> getBotEntitiesList() {
      return botEntities_;
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
     */
    public java.util.List<? extends com.treeleaf.anydone.entities.BotHousekeepingProto.BotEntityOrBuilder> 
        getBotEntitiesOrBuilderList() {
      return botEntities_;
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
     */
    public int getBotEntitiesCount() {
      return botEntities_.size();
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
     */
    public com.treeleaf.anydone.entities.BotHousekeepingProto.BotEntity getBotEntities(int index) {
      return botEntities_.get(index);
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
     */
    public com.treeleaf.anydone.entities.BotHousekeepingProto.BotEntityOrBuilder getBotEntitiesOrBuilder(
        int index) {
      return botEntities_.get(index);
    }
    private void ensureBotEntitiesIsMutable() {
      if (!botEntities_.isModifiable()) {
        botEntities_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(botEntities_);
       }
    }

    /**
     * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
     */
    private void setBotEntities(
        int index, com.treeleaf.anydone.entities.BotHousekeepingProto.BotEntity value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureBotEntitiesIsMutable();
      botEntities_.set(index, value);
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
     */
    private void setBotEntities(
        int index, com.treeleaf.anydone.entities.BotHousekeepingProto.BotEntity.Builder builderForValue) {
      ensureBotEntitiesIsMutable();
      botEntities_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
     */
    private void addBotEntities(com.treeleaf.anydone.entities.BotHousekeepingProto.BotEntity value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureBotEntitiesIsMutable();
      botEntities_.add(value);
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
     */
    private void addBotEntities(
        int index, com.treeleaf.anydone.entities.BotHousekeepingProto.BotEntity value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureBotEntitiesIsMutable();
      botEntities_.add(index, value);
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
     */
    private void addBotEntities(
        com.treeleaf.anydone.entities.BotHousekeepingProto.BotEntity.Builder builderForValue) {
      ensureBotEntitiesIsMutable();
      botEntities_.add(builderForValue.build());
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
     */
    private void addBotEntities(
        int index, com.treeleaf.anydone.entities.BotHousekeepingProto.BotEntity.Builder builderForValue) {
      ensureBotEntitiesIsMutable();
      botEntities_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
     */
    private void addAllBotEntities(
        java.lang.Iterable<? extends com.treeleaf.anydone.entities.BotHousekeepingProto.BotEntity> values) {
      ensureBotEntitiesIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, botEntities_);
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
     */
    private void clearBotEntities() {
      botEntities_ = emptyProtobufList();
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
     */
    private void removeBotEntities(int index) {
      ensureBotEntitiesIsMutable();
      botEntities_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (trainRequest_ != null) {
        output.writeMessage(1, getTrainRequest());
      }
      for (int i = 0; i < botEntities_.size(); i++) {
        output.writeMessage(2, botEntities_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (trainRequest_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTrainRequest());
      }
      for (int i = 0; i < botEntities_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, botEntities_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.treeleaf.anydone.entities.BotTrainProto.BotTrainRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.treeleaf.anydone.entities.BotTrainProto.BotTrainRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.BotTrainProto.BotTrainRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.treeleaf.anydone.entities.BotTrainProto.BotTrainRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.BotTrainProto.BotTrainRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.anydone.entities.BotTrainProto.BotTrainRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.BotTrainProto.BotTrainRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.anydone.entities.BotTrainProto.BotTrainRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.BotTrainProto.BotTrainRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.anydone.entities.BotTrainProto.BotTrainRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.treeleaf.anydone.entities.BotTrainProto.BotTrainRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code treeleaf.anydone.entities.BotTrainRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.treeleaf.anydone.entities.BotTrainProto.BotTrainRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:treeleaf.anydone.entities.BotTrainRequest)
        com.treeleaf.anydone.entities.BotTrainProto.BotTrainRequestOrBuilder {
      // Construct using com.treeleaf.anydone.entities.BotTrainProto.BotTrainRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional .treeleaf.anydone.entities.TrainRequest trainRequest = 1;</code>
       */
      public boolean hasTrainRequest() {
        return instance.hasTrainRequest();
      }
      /**
       * <code>optional .treeleaf.anydone.entities.TrainRequest trainRequest = 1;</code>
       */
      public com.treeleaf.anydone.entities.BotHousekeepingProto.TrainRequest getTrainRequest() {
        return instance.getTrainRequest();
      }
      /**
       * <code>optional .treeleaf.anydone.entities.TrainRequest trainRequest = 1;</code>
       */
      public Builder setTrainRequest(com.treeleaf.anydone.entities.BotHousekeepingProto.TrainRequest value) {
        copyOnWrite();
        instance.setTrainRequest(value);
        return this;
        }
      /**
       * <code>optional .treeleaf.anydone.entities.TrainRequest trainRequest = 1;</code>
       */
      public Builder setTrainRequest(
          com.treeleaf.anydone.entities.BotHousekeepingProto.TrainRequest.Builder builderForValue) {
        copyOnWrite();
        instance.setTrainRequest(builderForValue);
        return this;
      }
      /**
       * <code>optional .treeleaf.anydone.entities.TrainRequest trainRequest = 1;</code>
       */
      public Builder mergeTrainRequest(com.treeleaf.anydone.entities.BotHousekeepingProto.TrainRequest value) {
        copyOnWrite();
        instance.mergeTrainRequest(value);
        return this;
      }
      /**
       * <code>optional .treeleaf.anydone.entities.TrainRequest trainRequest = 1;</code>
       */
      public Builder clearTrainRequest() {  copyOnWrite();
        instance.clearTrainRequest();
        return this;
      }

      /**
       * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
       */
      public java.util.List<com.treeleaf.anydone.entities.BotHousekeepingProto.BotEntity> getBotEntitiesList() {
        return java.util.Collections.unmodifiableList(
            instance.getBotEntitiesList());
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
       */
      public int getBotEntitiesCount() {
        return instance.getBotEntitiesCount();
      }/**
       * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
       */
      public com.treeleaf.anydone.entities.BotHousekeepingProto.BotEntity getBotEntities(int index) {
        return instance.getBotEntities(index);
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
       */
      public Builder setBotEntities(
          int index, com.treeleaf.anydone.entities.BotHousekeepingProto.BotEntity value) {
        copyOnWrite();
        instance.setBotEntities(index, value);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
       */
      public Builder setBotEntities(
          int index, com.treeleaf.anydone.entities.BotHousekeepingProto.BotEntity.Builder builderForValue) {
        copyOnWrite();
        instance.setBotEntities(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
       */
      public Builder addBotEntities(com.treeleaf.anydone.entities.BotHousekeepingProto.BotEntity value) {
        copyOnWrite();
        instance.addBotEntities(value);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
       */
      public Builder addBotEntities(
          int index, com.treeleaf.anydone.entities.BotHousekeepingProto.BotEntity value) {
        copyOnWrite();
        instance.addBotEntities(index, value);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
       */
      public Builder addBotEntities(
          com.treeleaf.anydone.entities.BotHousekeepingProto.BotEntity.Builder builderForValue) {
        copyOnWrite();
        instance.addBotEntities(builderForValue);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
       */
      public Builder addBotEntities(
          int index, com.treeleaf.anydone.entities.BotHousekeepingProto.BotEntity.Builder builderForValue) {
        copyOnWrite();
        instance.addBotEntities(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
       */
      public Builder addAllBotEntities(
          java.lang.Iterable<? extends com.treeleaf.anydone.entities.BotHousekeepingProto.BotEntity> values) {
        copyOnWrite();
        instance.addAllBotEntities(values);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
       */
      public Builder clearBotEntities() {
        copyOnWrite();
        instance.clearBotEntities();
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.BotEntity botEntities = 2;</code>
       */
      public Builder removeBotEntities(int index) {
        copyOnWrite();
        instance.removeBotEntities(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:treeleaf.anydone.entities.BotTrainRequest)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.treeleaf.anydone.entities.BotTrainProto.BotTrainRequest();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          botEntities_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.treeleaf.anydone.entities.BotTrainProto.BotTrainRequest other = (com.treeleaf.anydone.entities.BotTrainProto.BotTrainRequest) arg1;
          trainRequest_ = visitor.visitMessage(trainRequest_, other.trainRequest_);
          botEntities_= visitor.visitList(botEntities_, other.botEntities_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  com.treeleaf.anydone.entities.BotHousekeepingProto.TrainRequest.Builder subBuilder = null;
                  if (trainRequest_ != null) {
                    subBuilder = trainRequest_.toBuilder();
                  }
                  trainRequest_ = input.readMessage(com.treeleaf.anydone.entities.BotHousekeepingProto.TrainRequest.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(trainRequest_);
                    trainRequest_ = subBuilder.buildPartial();
                  }

                  break;
                }
                case 18: {
                  if (!botEntities_.isModifiable()) {
                    botEntities_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(botEntities_);
                  }
                  botEntities_.add(
                      input.readMessage(com.treeleaf.anydone.entities.BotHousekeepingProto.BotEntity.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.treeleaf.anydone.entities.BotTrainProto.BotTrainRequest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:treeleaf.anydone.entities.BotTrainRequest)
    private static final com.treeleaf.anydone.entities.BotTrainProto.BotTrainRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BotTrainRequest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.treeleaf.anydone.entities.BotTrainProto.BotTrainRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<BotTrainRequest> PARSER;

    public static com.google.protobuf.Parser<BotTrainRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface BotTrainingCompleteEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:treeleaf.anydone.entities.BotTrainingCompleteEvent)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string serviceId = 1;</code>
     */
    java.lang.String getServiceId();
    /**
     * <code>optional string serviceId = 1;</code>
     */
    com.google.protobuf.ByteString
        getServiceIdBytes();

    /**
     * <code>optional string accountId = 2;</code>
     */
    java.lang.String getAccountId();
    /**
     * <code>optional string accountId = 2;</code>
     */
    com.google.protobuf.ByteString
        getAccountIdBytes();

    /**
     * <code>optional string botId = 3;</code>
     */
    java.lang.String getBotId();
    /**
     * <code>optional string botId = 3;</code>
     */
    com.google.protobuf.ByteString
        getBotIdBytes();

    /**
     * <code>optional int64 completedAt = 4;</code>
     */
    long getCompletedAt();

    /**
     * <code>optional string language = 5;</code>
     */
    java.lang.String getLanguage();
    /**
     * <code>optional string language = 5;</code>
     */
    com.google.protobuf.ByteString
        getLanguageBytes();

    /**
     * <code>optional string bucketName = 6;</code>
     */
    java.lang.String getBucketName();
    /**
     * <code>optional string bucketName = 6;</code>
     */
    com.google.protobuf.ByteString
        getBucketNameBytes();

    /**
     * <code>optional string trainedModelName = 7;</code>
     */
    java.lang.String getTrainedModelName();
    /**
     * <code>optional string trainedModelName = 7;</code>
     */
    com.google.protobuf.ByteString
        getTrainedModelNameBytes();

    /**
     * <code>optional string downloadPath = 8;</code>
     */
    java.lang.String getDownloadPath();
    /**
     * <code>optional string downloadPath = 8;</code>
     */
    com.google.protobuf.ByteString
        getDownloadPathBytes();

    /**
     * <code>optional int64 lastTrained = 9;</code>
     */
    long getLastTrained();

    /**
     * <code>optional int64 timeTakenToTrain = 10;</code>
     */
    long getTimeTakenToTrain();
  }
  /**
   * Protobuf type {@code treeleaf.anydone.entities.BotTrainingCompleteEvent}
   */
  public  static final class BotTrainingCompleteEvent extends
      com.google.protobuf.GeneratedMessageLite<
          BotTrainingCompleteEvent, BotTrainingCompleteEvent.Builder> implements
      // @@protoc_insertion_point(message_implements:treeleaf.anydone.entities.BotTrainingCompleteEvent)
      BotTrainingCompleteEventOrBuilder {
    private BotTrainingCompleteEvent() {
      serviceId_ = "";
      accountId_ = "";
      botId_ = "";
      language_ = "";
      bucketName_ = "";
      trainedModelName_ = "";
      downloadPath_ = "";
    }
    public static final int SERVICEID_FIELD_NUMBER = 1;
    private java.lang.String serviceId_;
    /**
     * <code>optional string serviceId = 1;</code>
     */
    public java.lang.String getServiceId() {
      return serviceId_;
    }
    /**
     * <code>optional string serviceId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServiceIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(serviceId_);
    }
    /**
     * <code>optional string serviceId = 1;</code>
     */
    private void setServiceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serviceId_ = value;
    }
    /**
     * <code>optional string serviceId = 1;</code>
     */
    private void clearServiceId() {
      
      serviceId_ = getDefaultInstance().getServiceId();
    }
    /**
     * <code>optional string serviceId = 1;</code>
     */
    private void setServiceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serviceId_ = value.toStringUtf8();
    }

    public static final int ACCOUNTID_FIELD_NUMBER = 2;
    private java.lang.String accountId_;
    /**
     * <code>optional string accountId = 2;</code>
     */
    public java.lang.String getAccountId() {
      return accountId_;
    }
    /**
     * <code>optional string accountId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAccountIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(accountId_);
    }
    /**
     * <code>optional string accountId = 2;</code>
     */
    private void setAccountId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accountId_ = value;
    }
    /**
     * <code>optional string accountId = 2;</code>
     */
    private void clearAccountId() {
      
      accountId_ = getDefaultInstance().getAccountId();
    }
    /**
     * <code>optional string accountId = 2;</code>
     */
    private void setAccountIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accountId_ = value.toStringUtf8();
    }

    public static final int BOTID_FIELD_NUMBER = 3;
    private java.lang.String botId_;
    /**
     * <code>optional string botId = 3;</code>
     */
    public java.lang.String getBotId() {
      return botId_;
    }
    /**
     * <code>optional string botId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBotIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(botId_);
    }
    /**
     * <code>optional string botId = 3;</code>
     */
    private void setBotId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      botId_ = value;
    }
    /**
     * <code>optional string botId = 3;</code>
     */
    private void clearBotId() {
      
      botId_ = getDefaultInstance().getBotId();
    }
    /**
     * <code>optional string botId = 3;</code>
     */
    private void setBotIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      botId_ = value.toStringUtf8();
    }

    public static final int COMPLETEDAT_FIELD_NUMBER = 4;
    private long completedAt_;
    /**
     * <code>optional int64 completedAt = 4;</code>
     */
    public long getCompletedAt() {
      return completedAt_;
    }
    /**
     * <code>optional int64 completedAt = 4;</code>
     */
    private void setCompletedAt(long value) {
      
      completedAt_ = value;
    }
    /**
     * <code>optional int64 completedAt = 4;</code>
     */
    private void clearCompletedAt() {
      
      completedAt_ = 0L;
    }

    public static final int LANGUAGE_FIELD_NUMBER = 5;
    private java.lang.String language_;
    /**
     * <code>optional string language = 5;</code>
     */
    public java.lang.String getLanguage() {
      return language_;
    }
    /**
     * <code>optional string language = 5;</code>
     */
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(language_);
    }
    /**
     * <code>optional string language = 5;</code>
     */
    private void setLanguage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      language_ = value;
    }
    /**
     * <code>optional string language = 5;</code>
     */
    private void clearLanguage() {
      
      language_ = getDefaultInstance().getLanguage();
    }
    /**
     * <code>optional string language = 5;</code>
     */
    private void setLanguageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      language_ = value.toStringUtf8();
    }

    public static final int BUCKETNAME_FIELD_NUMBER = 6;
    private java.lang.String bucketName_;
    /**
     * <code>optional string bucketName = 6;</code>
     */
    public java.lang.String getBucketName() {
      return bucketName_;
    }
    /**
     * <code>optional string bucketName = 6;</code>
     */
    public com.google.protobuf.ByteString
        getBucketNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(bucketName_);
    }
    /**
     * <code>optional string bucketName = 6;</code>
     */
    private void setBucketName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bucketName_ = value;
    }
    /**
     * <code>optional string bucketName = 6;</code>
     */
    private void clearBucketName() {
      
      bucketName_ = getDefaultInstance().getBucketName();
    }
    /**
     * <code>optional string bucketName = 6;</code>
     */
    private void setBucketNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bucketName_ = value.toStringUtf8();
    }

    public static final int TRAINEDMODELNAME_FIELD_NUMBER = 7;
    private java.lang.String trainedModelName_;
    /**
     * <code>optional string trainedModelName = 7;</code>
     */
    public java.lang.String getTrainedModelName() {
      return trainedModelName_;
    }
    /**
     * <code>optional string trainedModelName = 7;</code>
     */
    public com.google.protobuf.ByteString
        getTrainedModelNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(trainedModelName_);
    }
    /**
     * <code>optional string trainedModelName = 7;</code>
     */
    private void setTrainedModelName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      trainedModelName_ = value;
    }
    /**
     * <code>optional string trainedModelName = 7;</code>
     */
    private void clearTrainedModelName() {
      
      trainedModelName_ = getDefaultInstance().getTrainedModelName();
    }
    /**
     * <code>optional string trainedModelName = 7;</code>
     */
    private void setTrainedModelNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      trainedModelName_ = value.toStringUtf8();
    }

    public static final int DOWNLOADPATH_FIELD_NUMBER = 8;
    private java.lang.String downloadPath_;
    /**
     * <code>optional string downloadPath = 8;</code>
     */
    public java.lang.String getDownloadPath() {
      return downloadPath_;
    }
    /**
     * <code>optional string downloadPath = 8;</code>
     */
    public com.google.protobuf.ByteString
        getDownloadPathBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(downloadPath_);
    }
    /**
     * <code>optional string downloadPath = 8;</code>
     */
    private void setDownloadPath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      downloadPath_ = value;
    }
    /**
     * <code>optional string downloadPath = 8;</code>
     */
    private void clearDownloadPath() {
      
      downloadPath_ = getDefaultInstance().getDownloadPath();
    }
    /**
     * <code>optional string downloadPath = 8;</code>
     */
    private void setDownloadPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      downloadPath_ = value.toStringUtf8();
    }

    public static final int LASTTRAINED_FIELD_NUMBER = 9;
    private long lastTrained_;
    /**
     * <code>optional int64 lastTrained = 9;</code>
     */
    public long getLastTrained() {
      return lastTrained_;
    }
    /**
     * <code>optional int64 lastTrained = 9;</code>
     */
    private void setLastTrained(long value) {
      
      lastTrained_ = value;
    }
    /**
     * <code>optional int64 lastTrained = 9;</code>
     */
    private void clearLastTrained() {
      
      lastTrained_ = 0L;
    }

    public static final int TIMETAKENTOTRAIN_FIELD_NUMBER = 10;
    private long timeTakenToTrain_;
    /**
     * <code>optional int64 timeTakenToTrain = 10;</code>
     */
    public long getTimeTakenToTrain() {
      return timeTakenToTrain_;
    }
    /**
     * <code>optional int64 timeTakenToTrain = 10;</code>
     */
    private void setTimeTakenToTrain(long value) {
      
      timeTakenToTrain_ = value;
    }
    /**
     * <code>optional int64 timeTakenToTrain = 10;</code>
     */
    private void clearTimeTakenToTrain() {
      
      timeTakenToTrain_ = 0L;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!serviceId_.isEmpty()) {
        output.writeString(1, getServiceId());
      }
      if (!accountId_.isEmpty()) {
        output.writeString(2, getAccountId());
      }
      if (!botId_.isEmpty()) {
        output.writeString(3, getBotId());
      }
      if (completedAt_ != 0L) {
        output.writeInt64(4, completedAt_);
      }
      if (!language_.isEmpty()) {
        output.writeString(5, getLanguage());
      }
      if (!bucketName_.isEmpty()) {
        output.writeString(6, getBucketName());
      }
      if (!trainedModelName_.isEmpty()) {
        output.writeString(7, getTrainedModelName());
      }
      if (!downloadPath_.isEmpty()) {
        output.writeString(8, getDownloadPath());
      }
      if (lastTrained_ != 0L) {
        output.writeInt64(9, lastTrained_);
      }
      if (timeTakenToTrain_ != 0L) {
        output.writeInt64(10, timeTakenToTrain_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!serviceId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getServiceId());
      }
      if (!accountId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getAccountId());
      }
      if (!botId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getBotId());
      }
      if (completedAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, completedAt_);
      }
      if (!language_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getLanguage());
      }
      if (!bucketName_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getBucketName());
      }
      if (!trainedModelName_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getTrainedModelName());
      }
      if (!downloadPath_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(8, getDownloadPath());
      }
      if (lastTrained_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, lastTrained_);
      }
      if (timeTakenToTrain_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, timeTakenToTrain_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.treeleaf.anydone.entities.BotTrainProto.BotTrainingCompleteEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.treeleaf.anydone.entities.BotTrainProto.BotTrainingCompleteEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.BotTrainProto.BotTrainingCompleteEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.treeleaf.anydone.entities.BotTrainProto.BotTrainingCompleteEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.BotTrainProto.BotTrainingCompleteEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.anydone.entities.BotTrainProto.BotTrainingCompleteEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.BotTrainProto.BotTrainingCompleteEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.anydone.entities.BotTrainProto.BotTrainingCompleteEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.BotTrainProto.BotTrainingCompleteEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.anydone.entities.BotTrainProto.BotTrainingCompleteEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.treeleaf.anydone.entities.BotTrainProto.BotTrainingCompleteEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code treeleaf.anydone.entities.BotTrainingCompleteEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.treeleaf.anydone.entities.BotTrainProto.BotTrainingCompleteEvent, Builder> implements
        // @@protoc_insertion_point(builder_implements:treeleaf.anydone.entities.BotTrainingCompleteEvent)
        com.treeleaf.anydone.entities.BotTrainProto.BotTrainingCompleteEventOrBuilder {
      // Construct using com.treeleaf.anydone.entities.BotTrainProto.BotTrainingCompleteEvent.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string serviceId = 1;</code>
       */
      public java.lang.String getServiceId() {
        return instance.getServiceId();
      }
      /**
       * <code>optional string serviceId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServiceIdBytes() {
        return instance.getServiceIdBytes();
      }
      /**
       * <code>optional string serviceId = 1;</code>
       */
      public Builder setServiceId(
          java.lang.String value) {
        copyOnWrite();
        instance.setServiceId(value);
        return this;
      }
      /**
       * <code>optional string serviceId = 1;</code>
       */
      public Builder clearServiceId() {
        copyOnWrite();
        instance.clearServiceId();
        return this;
      }
      /**
       * <code>optional string serviceId = 1;</code>
       */
      public Builder setServiceIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setServiceIdBytes(value);
        return this;
      }

      /**
       * <code>optional string accountId = 2;</code>
       */
      public java.lang.String getAccountId() {
        return instance.getAccountId();
      }
      /**
       * <code>optional string accountId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAccountIdBytes() {
        return instance.getAccountIdBytes();
      }
      /**
       * <code>optional string accountId = 2;</code>
       */
      public Builder setAccountId(
          java.lang.String value) {
        copyOnWrite();
        instance.setAccountId(value);
        return this;
      }
      /**
       * <code>optional string accountId = 2;</code>
       */
      public Builder clearAccountId() {
        copyOnWrite();
        instance.clearAccountId();
        return this;
      }
      /**
       * <code>optional string accountId = 2;</code>
       */
      public Builder setAccountIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAccountIdBytes(value);
        return this;
      }

      /**
       * <code>optional string botId = 3;</code>
       */
      public java.lang.String getBotId() {
        return instance.getBotId();
      }
      /**
       * <code>optional string botId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getBotIdBytes() {
        return instance.getBotIdBytes();
      }
      /**
       * <code>optional string botId = 3;</code>
       */
      public Builder setBotId(
          java.lang.String value) {
        copyOnWrite();
        instance.setBotId(value);
        return this;
      }
      /**
       * <code>optional string botId = 3;</code>
       */
      public Builder clearBotId() {
        copyOnWrite();
        instance.clearBotId();
        return this;
      }
      /**
       * <code>optional string botId = 3;</code>
       */
      public Builder setBotIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBotIdBytes(value);
        return this;
      }

      /**
       * <code>optional int64 completedAt = 4;</code>
       */
      public long getCompletedAt() {
        return instance.getCompletedAt();
      }
      /**
       * <code>optional int64 completedAt = 4;</code>
       */
      public Builder setCompletedAt(long value) {
        copyOnWrite();
        instance.setCompletedAt(value);
        return this;
      }
      /**
       * <code>optional int64 completedAt = 4;</code>
       */
      public Builder clearCompletedAt() {
        copyOnWrite();
        instance.clearCompletedAt();
        return this;
      }

      /**
       * <code>optional string language = 5;</code>
       */
      public java.lang.String getLanguage() {
        return instance.getLanguage();
      }
      /**
       * <code>optional string language = 5;</code>
       */
      public com.google.protobuf.ByteString
          getLanguageBytes() {
        return instance.getLanguageBytes();
      }
      /**
       * <code>optional string language = 5;</code>
       */
      public Builder setLanguage(
          java.lang.String value) {
        copyOnWrite();
        instance.setLanguage(value);
        return this;
      }
      /**
       * <code>optional string language = 5;</code>
       */
      public Builder clearLanguage() {
        copyOnWrite();
        instance.clearLanguage();
        return this;
      }
      /**
       * <code>optional string language = 5;</code>
       */
      public Builder setLanguageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLanguageBytes(value);
        return this;
      }

      /**
       * <code>optional string bucketName = 6;</code>
       */
      public java.lang.String getBucketName() {
        return instance.getBucketName();
      }
      /**
       * <code>optional string bucketName = 6;</code>
       */
      public com.google.protobuf.ByteString
          getBucketNameBytes() {
        return instance.getBucketNameBytes();
      }
      /**
       * <code>optional string bucketName = 6;</code>
       */
      public Builder setBucketName(
          java.lang.String value) {
        copyOnWrite();
        instance.setBucketName(value);
        return this;
      }
      /**
       * <code>optional string bucketName = 6;</code>
       */
      public Builder clearBucketName() {
        copyOnWrite();
        instance.clearBucketName();
        return this;
      }
      /**
       * <code>optional string bucketName = 6;</code>
       */
      public Builder setBucketNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBucketNameBytes(value);
        return this;
      }

      /**
       * <code>optional string trainedModelName = 7;</code>
       */
      public java.lang.String getTrainedModelName() {
        return instance.getTrainedModelName();
      }
      /**
       * <code>optional string trainedModelName = 7;</code>
       */
      public com.google.protobuf.ByteString
          getTrainedModelNameBytes() {
        return instance.getTrainedModelNameBytes();
      }
      /**
       * <code>optional string trainedModelName = 7;</code>
       */
      public Builder setTrainedModelName(
          java.lang.String value) {
        copyOnWrite();
        instance.setTrainedModelName(value);
        return this;
      }
      /**
       * <code>optional string trainedModelName = 7;</code>
       */
      public Builder clearTrainedModelName() {
        copyOnWrite();
        instance.clearTrainedModelName();
        return this;
      }
      /**
       * <code>optional string trainedModelName = 7;</code>
       */
      public Builder setTrainedModelNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTrainedModelNameBytes(value);
        return this;
      }

      /**
       * <code>optional string downloadPath = 8;</code>
       */
      public java.lang.String getDownloadPath() {
        return instance.getDownloadPath();
      }
      /**
       * <code>optional string downloadPath = 8;</code>
       */
      public com.google.protobuf.ByteString
          getDownloadPathBytes() {
        return instance.getDownloadPathBytes();
      }
      /**
       * <code>optional string downloadPath = 8;</code>
       */
      public Builder setDownloadPath(
          java.lang.String value) {
        copyOnWrite();
        instance.setDownloadPath(value);
        return this;
      }
      /**
       * <code>optional string downloadPath = 8;</code>
       */
      public Builder clearDownloadPath() {
        copyOnWrite();
        instance.clearDownloadPath();
        return this;
      }
      /**
       * <code>optional string downloadPath = 8;</code>
       */
      public Builder setDownloadPathBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDownloadPathBytes(value);
        return this;
      }

      /**
       * <code>optional int64 lastTrained = 9;</code>
       */
      public long getLastTrained() {
        return instance.getLastTrained();
      }
      /**
       * <code>optional int64 lastTrained = 9;</code>
       */
      public Builder setLastTrained(long value) {
        copyOnWrite();
        instance.setLastTrained(value);
        return this;
      }
      /**
       * <code>optional int64 lastTrained = 9;</code>
       */
      public Builder clearLastTrained() {
        copyOnWrite();
        instance.clearLastTrained();
        return this;
      }

      /**
       * <code>optional int64 timeTakenToTrain = 10;</code>
       */
      public long getTimeTakenToTrain() {
        return instance.getTimeTakenToTrain();
      }
      /**
       * <code>optional int64 timeTakenToTrain = 10;</code>
       */
      public Builder setTimeTakenToTrain(long value) {
        copyOnWrite();
        instance.setTimeTakenToTrain(value);
        return this;
      }
      /**
       * <code>optional int64 timeTakenToTrain = 10;</code>
       */
      public Builder clearTimeTakenToTrain() {
        copyOnWrite();
        instance.clearTimeTakenToTrain();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:treeleaf.anydone.entities.BotTrainingCompleteEvent)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.treeleaf.anydone.entities.BotTrainProto.BotTrainingCompleteEvent();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.treeleaf.anydone.entities.BotTrainProto.BotTrainingCompleteEvent other = (com.treeleaf.anydone.entities.BotTrainProto.BotTrainingCompleteEvent) arg1;
          serviceId_ = visitor.visitString(!serviceId_.isEmpty(), serviceId_,
              !other.serviceId_.isEmpty(), other.serviceId_);
          accountId_ = visitor.visitString(!accountId_.isEmpty(), accountId_,
              !other.accountId_.isEmpty(), other.accountId_);
          botId_ = visitor.visitString(!botId_.isEmpty(), botId_,
              !other.botId_.isEmpty(), other.botId_);
          completedAt_ = visitor.visitLong(completedAt_ != 0L, completedAt_,
              other.completedAt_ != 0L, other.completedAt_);
          language_ = visitor.visitString(!language_.isEmpty(), language_,
              !other.language_.isEmpty(), other.language_);
          bucketName_ = visitor.visitString(!bucketName_.isEmpty(), bucketName_,
              !other.bucketName_.isEmpty(), other.bucketName_);
          trainedModelName_ = visitor.visitString(!trainedModelName_.isEmpty(), trainedModelName_,
              !other.trainedModelName_.isEmpty(), other.trainedModelName_);
          downloadPath_ = visitor.visitString(!downloadPath_.isEmpty(), downloadPath_,
              !other.downloadPath_.isEmpty(), other.downloadPath_);
          lastTrained_ = visitor.visitLong(lastTrained_ != 0L, lastTrained_,
              other.lastTrained_ != 0L, other.lastTrained_);
          timeTakenToTrain_ = visitor.visitLong(timeTakenToTrain_ != 0L, timeTakenToTrain_,
              other.timeTakenToTrain_ != 0L, other.timeTakenToTrain_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  serviceId_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  accountId_ = s;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  botId_ = s;
                  break;
                }
                case 32: {

                  completedAt_ = input.readInt64();
                  break;
                }
                case 42: {
                  String s = input.readStringRequireUtf8();

                  language_ = s;
                  break;
                }
                case 50: {
                  String s = input.readStringRequireUtf8();

                  bucketName_ = s;
                  break;
                }
                case 58: {
                  String s = input.readStringRequireUtf8();

                  trainedModelName_ = s;
                  break;
                }
                case 66: {
                  String s = input.readStringRequireUtf8();

                  downloadPath_ = s;
                  break;
                }
                case 72: {

                  lastTrained_ = input.readInt64();
                  break;
                }
                case 80: {

                  timeTakenToTrain_ = input.readInt64();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.treeleaf.anydone.entities.BotTrainProto.BotTrainingCompleteEvent.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:treeleaf.anydone.entities.BotTrainingCompleteEvent)
    private static final com.treeleaf.anydone.entities.BotTrainProto.BotTrainingCompleteEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BotTrainingCompleteEvent();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.treeleaf.anydone.entities.BotTrainProto.BotTrainingCompleteEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<BotTrainingCompleteEvent> PARSER;

    public static com.google.protobuf.Parser<BotTrainingCompleteEvent> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
