// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_notification.proto

package com.treeleaf.anydone.entities;

public final class EventNotificationProto {
  private EventNotificationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code treeleaf.anydone.entities.EventNotificationType}
   */
  public enum EventNotificationType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>UNKNOWN_EVENT_NOTIFICATION = 0;</code>
     */
    UNKNOWN_EVENT_NOTIFICATION(0),
    /**
     * <code>BOT_TRAIN_NOTIFICATION = 1;</code>
     */
    BOT_TRAIN_NOTIFICATION(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN_EVENT_NOTIFICATION = 0;</code>
     */
    public static final int UNKNOWN_EVENT_NOTIFICATION_VALUE = 0;
    /**
     * <code>BOT_TRAIN_NOTIFICATION = 1;</code>
     */
    public static final int BOT_TRAIN_NOTIFICATION_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static EventNotificationType valueOf(int value) {
      return forNumber(value);
    }

    public static EventNotificationType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_EVENT_NOTIFICATION;
        case 1: return BOT_TRAIN_NOTIFICATION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EventNotificationType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EventNotificationType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EventNotificationType>() {
            public EventNotificationType findValueByNumber(int number) {
              return EventNotificationType.forNumber(number);
            }
          };

    private final int value;

    private EventNotificationType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:treeleaf.anydone.entities.EventNotificationType)
  }

  public interface EventNotificationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:treeleaf.anydone.entities.EventNotification)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .treeleaf.anydone.entities.EventNotificationType eventNotificationType = 1;</code>
     */
    int getEventNotificationTypeValue();
    /**
     * <code>optional .treeleaf.anydone.entities.EventNotificationType eventNotificationType = 1;</code>
     */
    EventNotificationType getEventNotificationType();

    /**
     * <code>optional bool error = 2;</code>
     */
    boolean getError();

    /**
     * <code>optional bool success = 3;</code>
     */
    boolean getSuccess();

    /**
     * <code>optional .treeleaf.protos.ErrorCode errorCode = 4;</code>
     */
    int getErrorCodeValue();
    /**
     * <code>optional .treeleaf.protos.ErrorCode errorCode = 4;</code>
     */
    TreeleafProto.ErrorCode getErrorCode();

    /**
     * <code>optional string msg = 5;</code>
     */
    String getMsg();
    /**
     * <code>optional string msg = 5;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>optional string accountId = 6;</code>
     */
    String getAccountId();
    /**
     * <code>optional string accountId = 6;</code>
     */
    com.google.protobuf.ByteString
        getAccountIdBytes();

    /**
     * <code>optional string refId = 7;</code>
     */
    String getRefId();
    /**
     * <code>optional string refId = 7;</code>
     */
    com.google.protobuf.ByteString
        getRefIdBytes();
  }
  /**
   * Protobuf type {@code treeleaf.anydone.entities.EventNotification}
   */
  public  static final class EventNotification extends
      com.google.protobuf.GeneratedMessageLite<
          EventNotification, EventNotification.Builder> implements
      // @@protoc_insertion_point(message_implements:treeleaf.anydone.entities.EventNotification)
      EventNotificationOrBuilder {
    private EventNotification() {
      msg_ = "";
      accountId_ = "";
      refId_ = "";
    }
    public static final int EVENTNOTIFICATIONTYPE_FIELD_NUMBER = 1;
    private int eventNotificationType_;
    /**
     * <code>optional .treeleaf.anydone.entities.EventNotificationType eventNotificationType = 1;</code>
     */
    public int getEventNotificationTypeValue() {
      return eventNotificationType_;
    }
    /**
     * <code>optional .treeleaf.anydone.entities.EventNotificationType eventNotificationType = 1;</code>
     */
    public EventNotificationType getEventNotificationType() {
      EventNotificationType result = EventNotificationType.forNumber(eventNotificationType_);
      return result == null ? EventNotificationType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .treeleaf.anydone.entities.EventNotificationType eventNotificationType = 1;</code>
     */
    private void setEventNotificationTypeValue(int value) {
        eventNotificationType_ = value;
    }
    /**
     * <code>optional .treeleaf.anydone.entities.EventNotificationType eventNotificationType = 1;</code>
     */
    private void setEventNotificationType(EventNotificationType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      eventNotificationType_ = value.getNumber();
    }
    /**
     * <code>optional .treeleaf.anydone.entities.EventNotificationType eventNotificationType = 1;</code>
     */
    private void clearEventNotificationType() {
      
      eventNotificationType_ = 0;
    }

    public static final int ERROR_FIELD_NUMBER = 2;
    private boolean error_;
    /**
     * <code>optional bool error = 2;</code>
     */
    public boolean getError() {
      return error_;
    }
    /**
     * <code>optional bool error = 2;</code>
     */
    private void setError(boolean value) {
      
      error_ = value;
    }
    /**
     * <code>optional bool error = 2;</code>
     */
    private void clearError() {
      
      error_ = false;
    }

    public static final int SUCCESS_FIELD_NUMBER = 3;
    private boolean success_;
    /**
     * <code>optional bool success = 3;</code>
     */
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>optional bool success = 3;</code>
     */
    private void setSuccess(boolean value) {
      
      success_ = value;
    }
    /**
     * <code>optional bool success = 3;</code>
     */
    private void clearSuccess() {
      
      success_ = false;
    }

    public static final int ERRORCODE_FIELD_NUMBER = 4;
    private int errorCode_;
    /**
     * <code>optional .treeleaf.protos.ErrorCode errorCode = 4;</code>
     */
    public int getErrorCodeValue() {
      return errorCode_;
    }
    /**
     * <code>optional .treeleaf.protos.ErrorCode errorCode = 4;</code>
     */
    public TreeleafProto.ErrorCode getErrorCode() {
      TreeleafProto.ErrorCode result = TreeleafProto.ErrorCode.forNumber(errorCode_);
      return result == null ? TreeleafProto.ErrorCode.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .treeleaf.protos.ErrorCode errorCode = 4;</code>
     */
    private void setErrorCodeValue(int value) {
        errorCode_ = value;
    }
    /**
     * <code>optional .treeleaf.protos.ErrorCode errorCode = 4;</code>
     */
    private void setErrorCode(TreeleafProto.ErrorCode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      errorCode_ = value.getNumber();
    }
    /**
     * <code>optional .treeleaf.protos.ErrorCode errorCode = 4;</code>
     */
    private void clearErrorCode() {
      
      errorCode_ = 0;
    }

    public static final int MSG_FIELD_NUMBER = 5;
    private String msg_;
    /**
     * <code>optional string msg = 5;</code>
     */
    public String getMsg() {
      return msg_;
    }
    /**
     * <code>optional string msg = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(msg_);
    }
    /**
     * <code>optional string msg = 5;</code>
     */
    private void setMsg(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msg_ = value;
    }
    /**
     * <code>optional string msg = 5;</code>
     */
    private void clearMsg() {
      
      msg_ = getDefaultInstance().getMsg();
    }
    /**
     * <code>optional string msg = 5;</code>
     */
    private void setMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msg_ = value.toStringUtf8();
    }

    public static final int ACCOUNTID_FIELD_NUMBER = 6;
    private String accountId_;
    /**
     * <code>optional string accountId = 6;</code>
     */
    public String getAccountId() {
      return accountId_;
    }
    /**
     * <code>optional string accountId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getAccountIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(accountId_);
    }
    /**
     * <code>optional string accountId = 6;</code>
     */
    private void setAccountId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accountId_ = value;
    }
    /**
     * <code>optional string accountId = 6;</code>
     */
    private void clearAccountId() {
      
      accountId_ = getDefaultInstance().getAccountId();
    }
    /**
     * <code>optional string accountId = 6;</code>
     */
    private void setAccountIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accountId_ = value.toStringUtf8();
    }

    public static final int REFID_FIELD_NUMBER = 7;
    private String refId_;
    /**
     * <code>optional string refId = 7;</code>
     */
    public String getRefId() {
      return refId_;
    }
    /**
     * <code>optional string refId = 7;</code>
     */
    public com.google.protobuf.ByteString
        getRefIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(refId_);
    }
    /**
     * <code>optional string refId = 7;</code>
     */
    private void setRefId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      refId_ = value;
    }
    /**
     * <code>optional string refId = 7;</code>
     */
    private void clearRefId() {
      
      refId_ = getDefaultInstance().getRefId();
    }
    /**
     * <code>optional string refId = 7;</code>
     */
    private void setRefIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      refId_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (eventNotificationType_ != EventNotificationType.UNKNOWN_EVENT_NOTIFICATION.getNumber()) {
        output.writeEnum(1, eventNotificationType_);
      }
      if (error_ != false) {
        output.writeBool(2, error_);
      }
      if (success_ != false) {
        output.writeBool(3, success_);
      }
      if (errorCode_ != TreeleafProto.ErrorCode.UNKNOWN_ERROR.getNumber()) {
        output.writeEnum(4, errorCode_);
      }
      if (!msg_.isEmpty()) {
        output.writeString(5, getMsg());
      }
      if (!accountId_.isEmpty()) {
        output.writeString(6, getAccountId());
      }
      if (!refId_.isEmpty()) {
        output.writeString(7, getRefId());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (eventNotificationType_ != EventNotificationType.UNKNOWN_EVENT_NOTIFICATION.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, eventNotificationType_);
      }
      if (error_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, error_);
      }
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, success_);
      }
      if (errorCode_ != TreeleafProto.ErrorCode.UNKNOWN_ERROR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, errorCode_);
      }
      if (!msg_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getMsg());
      }
      if (!accountId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getAccountId());
      }
      if (!refId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getRefId());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static EventNotification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static EventNotification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static EventNotification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static EventNotification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static EventNotification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static EventNotification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static EventNotification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static EventNotification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static EventNotification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static EventNotification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EventNotification prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code treeleaf.anydone.entities.EventNotification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          EventNotification, Builder> implements
        // @@protoc_insertion_point(builder_implements:treeleaf.anydone.entities.EventNotification)
        EventNotificationOrBuilder {
      // Construct using com.treeleaf.anydone.entities.EventNotificationProto.EventNotification.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional .treeleaf.anydone.entities.EventNotificationType eventNotificationType = 1;</code>
       */
      public int getEventNotificationTypeValue() {
        return instance.getEventNotificationTypeValue();
      }
      /**
       * <code>optional .treeleaf.anydone.entities.EventNotificationType eventNotificationType = 1;</code>
       */
      public Builder setEventNotificationTypeValue(int value) {
        copyOnWrite();
        instance.setEventNotificationTypeValue(value);
        return this;
      }
      /**
       * <code>optional .treeleaf.anydone.entities.EventNotificationType eventNotificationType = 1;</code>
       */
      public EventNotificationType getEventNotificationType() {
        return instance.getEventNotificationType();
      }
      /**
       * <code>optional .treeleaf.anydone.entities.EventNotificationType eventNotificationType = 1;</code>
       */
      public Builder setEventNotificationType(EventNotificationType value) {
        copyOnWrite();
        instance.setEventNotificationType(value);
        return this;
      }
      /**
       * <code>optional .treeleaf.anydone.entities.EventNotificationType eventNotificationType = 1;</code>
       */
      public Builder clearEventNotificationType() {
        copyOnWrite();
        instance.clearEventNotificationType();
        return this;
      }

      /**
       * <code>optional bool error = 2;</code>
       */
      public boolean getError() {
        return instance.getError();
      }
      /**
       * <code>optional bool error = 2;</code>
       */
      public Builder setError(boolean value) {
        copyOnWrite();
        instance.setError(value);
        return this;
      }
      /**
       * <code>optional bool error = 2;</code>
       */
      public Builder clearError() {
        copyOnWrite();
        instance.clearError();
        return this;
      }

      /**
       * <code>optional bool success = 3;</code>
       */
      public boolean getSuccess() {
        return instance.getSuccess();
      }
      /**
       * <code>optional bool success = 3;</code>
       */
      public Builder setSuccess(boolean value) {
        copyOnWrite();
        instance.setSuccess(value);
        return this;
      }
      /**
       * <code>optional bool success = 3;</code>
       */
      public Builder clearSuccess() {
        copyOnWrite();
        instance.clearSuccess();
        return this;
      }

      /**
       * <code>optional .treeleaf.protos.ErrorCode errorCode = 4;</code>
       */
      public int getErrorCodeValue() {
        return instance.getErrorCodeValue();
      }
      /**
       * <code>optional .treeleaf.protos.ErrorCode errorCode = 4;</code>
       */
      public Builder setErrorCodeValue(int value) {
        copyOnWrite();
        instance.setErrorCodeValue(value);
        return this;
      }
      /**
       * <code>optional .treeleaf.protos.ErrorCode errorCode = 4;</code>
       */
      public TreeleafProto.ErrorCode getErrorCode() {
        return instance.getErrorCode();
      }
      /**
       * <code>optional .treeleaf.protos.ErrorCode errorCode = 4;</code>
       */
      public Builder setErrorCode(TreeleafProto.ErrorCode value) {
        copyOnWrite();
        instance.setErrorCode(value);
        return this;
      }
      /**
       * <code>optional .treeleaf.protos.ErrorCode errorCode = 4;</code>
       */
      public Builder clearErrorCode() {
        copyOnWrite();
        instance.clearErrorCode();
        return this;
      }

      /**
       * <code>optional string msg = 5;</code>
       */
      public String getMsg() {
        return instance.getMsg();
      }
      /**
       * <code>optional string msg = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        return instance.getMsgBytes();
      }
      /**
       * <code>optional string msg = 5;</code>
       */
      public Builder setMsg(
          String value) {
        copyOnWrite();
        instance.setMsg(value);
        return this;
      }
      /**
       * <code>optional string msg = 5;</code>
       */
      public Builder clearMsg() {
        copyOnWrite();
        instance.clearMsg();
        return this;
      }
      /**
       * <code>optional string msg = 5;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMsgBytes(value);
        return this;
      }

      /**
       * <code>optional string accountId = 6;</code>
       */
      public String getAccountId() {
        return instance.getAccountId();
      }
      /**
       * <code>optional string accountId = 6;</code>
       */
      public com.google.protobuf.ByteString
          getAccountIdBytes() {
        return instance.getAccountIdBytes();
      }
      /**
       * <code>optional string accountId = 6;</code>
       */
      public Builder setAccountId(
          String value) {
        copyOnWrite();
        instance.setAccountId(value);
        return this;
      }
      /**
       * <code>optional string accountId = 6;</code>
       */
      public Builder clearAccountId() {
        copyOnWrite();
        instance.clearAccountId();
        return this;
      }
      /**
       * <code>optional string accountId = 6;</code>
       */
      public Builder setAccountIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAccountIdBytes(value);
        return this;
      }

      /**
       * <code>optional string refId = 7;</code>
       */
      public String getRefId() {
        return instance.getRefId();
      }
      /**
       * <code>optional string refId = 7;</code>
       */
      public com.google.protobuf.ByteString
          getRefIdBytes() {
        return instance.getRefIdBytes();
      }
      /**
       * <code>optional string refId = 7;</code>
       */
      public Builder setRefId(
          String value) {
        copyOnWrite();
        instance.setRefId(value);
        return this;
      }
      /**
       * <code>optional string refId = 7;</code>
       */
      public Builder clearRefId() {
        copyOnWrite();
        instance.clearRefId();
        return this;
      }
      /**
       * <code>optional string refId = 7;</code>
       */
      public Builder setRefIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setRefIdBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:treeleaf.anydone.entities.EventNotification)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new EventNotification();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          EventNotification other = (EventNotification) arg1;
          eventNotificationType_ = visitor.visitInt(eventNotificationType_ != 0, eventNotificationType_,    other.eventNotificationType_ != 0, other.eventNotificationType_);
          error_ = visitor.visitBoolean(error_ != false, error_,
              other.error_ != false, other.error_);
          success_ = visitor.visitBoolean(success_ != false, success_,
              other.success_ != false, other.success_);
          errorCode_ = visitor.visitInt(errorCode_ != 0, errorCode_,    other.errorCode_ != 0, other.errorCode_);
          msg_ = visitor.visitString(!msg_.isEmpty(), msg_,
              !other.msg_.isEmpty(), other.msg_);
          accountId_ = visitor.visitString(!accountId_.isEmpty(), accountId_,
              !other.accountId_.isEmpty(), other.accountId_);
          refId_ = visitor.visitString(!refId_.isEmpty(), refId_,
              !other.refId_.isEmpty(), other.refId_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  int rawValue = input.readEnum();

                  eventNotificationType_ = rawValue;
                  break;
                }
                case 16: {

                  error_ = input.readBool();
                  break;
                }
                case 24: {

                  success_ = input.readBool();
                  break;
                }
                case 32: {
                  int rawValue = input.readEnum();

                  errorCode_ = rawValue;
                  break;
                }
                case 42: {
                  String s = input.readStringRequireUtf8();

                  msg_ = s;
                  break;
                }
                case 50: {
                  String s = input.readStringRequireUtf8();

                  accountId_ = s;
                  break;
                }
                case 58: {
                  String s = input.readStringRequireUtf8();

                  refId_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (EventNotification.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:treeleaf.anydone.entities.EventNotification)
    private static final EventNotification DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EventNotification();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static EventNotification getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<EventNotification> PARSER;

    public static com.google.protobuf.Parser<EventNotification> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
