// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inbox.proto

package com.treeleaf.anydone.entities;

public final class InboxProto {
  private InboxProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface InboxParticipantOrBuilder extends
      // @@protoc_insertion_point(interface_extends:treeleaf.anydone.entities.InboxParticipant)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .treeleaf.anydone.entities.InboxParticipant.InboxRole role = 1;</code>
     */
    int getRoleValue();
    /**
     * <code>optional .treeleaf.anydone.entities.InboxParticipant.InboxRole role = 1;</code>
     */
    com.treeleaf.anydone.entities.InboxProto.InboxParticipant.InboxRole getRole();

    /**
     * <code>optional string participantId = 2;</code>
     */
    java.lang.String getParticipantId();
    /**
     * <code>optional string participantId = 2;</code>
     */
    com.google.protobuf.ByteString
        getParticipantIdBytes();

    /**
     * <code>optional .treeleaf.anydone.entities.User user = 3;</code>
     */
    boolean hasUser();
    /**
     * <code>optional .treeleaf.anydone.entities.User user = 3;</code>
     */
    com.treeleaf.anydone.entities.UserProto.User getUser();
  }
  /**
   * Protobuf type {@code treeleaf.anydone.entities.InboxParticipant}
   */
  public  static final class InboxParticipant extends
      com.google.protobuf.GeneratedMessageLite<
          InboxParticipant, InboxParticipant.Builder> implements
      // @@protoc_insertion_point(message_implements:treeleaf.anydone.entities.InboxParticipant)
      InboxParticipantOrBuilder {
    private InboxParticipant() {
      participantId_ = "";
    }
    /**
     * Protobuf enum {@code treeleaf.anydone.entities.InboxParticipant.InboxRole}
     */
    public enum InboxRole
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>UNKNOWN_INBOX_ROLE = 0;</code>
       */
      UNKNOWN_INBOX_ROLE(0),
      /**
       * <code>INBOX_ADMIN = 1;</code>
       */
      INBOX_ADMIN(1),
      /**
       * <code>INBOX_MEMBER = 2;</code>
       */
      INBOX_MEMBER(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN_INBOX_ROLE = 0;</code>
       */
      public static final int UNKNOWN_INBOX_ROLE_VALUE = 0;
      /**
       * <code>INBOX_ADMIN = 1;</code>
       */
      public static final int INBOX_ADMIN_VALUE = 1;
      /**
       * <code>INBOX_MEMBER = 2;</code>
       */
      public static final int INBOX_MEMBER_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static InboxRole valueOf(int value) {
        return forNumber(value);
      }

      public static InboxRole forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN_INBOX_ROLE;
          case 1: return INBOX_ADMIN;
          case 2: return INBOX_MEMBER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<InboxRole>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          InboxRole> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<InboxRole>() {
              public InboxRole findValueByNumber(int number) {
                return InboxRole.forNumber(number);
              }
            };

      private final int value;

      private InboxRole(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:treeleaf.anydone.entities.InboxParticipant.InboxRole)
    }

    public static final int ROLE_FIELD_NUMBER = 1;
    private int role_;
    /**
     * <code>optional .treeleaf.anydone.entities.InboxParticipant.InboxRole role = 1;</code>
     */
    public int getRoleValue() {
      return role_;
    }
    /**
     * <code>optional .treeleaf.anydone.entities.InboxParticipant.InboxRole role = 1;</code>
     */
    public com.treeleaf.anydone.entities.InboxProto.InboxParticipant.InboxRole getRole() {
      com.treeleaf.anydone.entities.InboxProto.InboxParticipant.InboxRole result = com.treeleaf.anydone.entities.InboxProto.InboxParticipant.InboxRole.forNumber(role_);
      return result == null ? com.treeleaf.anydone.entities.InboxProto.InboxParticipant.InboxRole.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .treeleaf.anydone.entities.InboxParticipant.InboxRole role = 1;</code>
     */
    private void setRoleValue(int value) {
        role_ = value;
    }
    /**
     * <code>optional .treeleaf.anydone.entities.InboxParticipant.InboxRole role = 1;</code>
     */
    private void setRole(com.treeleaf.anydone.entities.InboxProto.InboxParticipant.InboxRole value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      role_ = value.getNumber();
    }
    /**
     * <code>optional .treeleaf.anydone.entities.InboxParticipant.InboxRole role = 1;</code>
     */
    private void clearRole() {
      
      role_ = 0;
    }

    public static final int PARTICIPANTID_FIELD_NUMBER = 2;
    private java.lang.String participantId_;
    /**
     * <code>optional string participantId = 2;</code>
     */
    public java.lang.String getParticipantId() {
      return participantId_;
    }
    /**
     * <code>optional string participantId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getParticipantIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(participantId_);
    }
    /**
     * <code>optional string participantId = 2;</code>
     */
    private void setParticipantId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      participantId_ = value;
    }
    /**
     * <code>optional string participantId = 2;</code>
     */
    private void clearParticipantId() {
      
      participantId_ = getDefaultInstance().getParticipantId();
    }
    /**
     * <code>optional string participantId = 2;</code>
     */
    private void setParticipantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      participantId_ = value.toStringUtf8();
    }

    public static final int USER_FIELD_NUMBER = 3;
    private com.treeleaf.anydone.entities.UserProto.User user_;
    /**
     * <code>optional .treeleaf.anydone.entities.User user = 3;</code>
     */
    public boolean hasUser() {
      return user_ != null;
    }
    /**
     * <code>optional .treeleaf.anydone.entities.User user = 3;</code>
     */
    public com.treeleaf.anydone.entities.UserProto.User getUser() {
      return user_ == null ? com.treeleaf.anydone.entities.UserProto.User.getDefaultInstance() : user_;
    }
    /**
     * <code>optional .treeleaf.anydone.entities.User user = 3;</code>
     */
    private void setUser(com.treeleaf.anydone.entities.UserProto.User value) {
      if (value == null) {
        throw new NullPointerException();
      }
      user_ = value;
      
      }
    /**
     * <code>optional .treeleaf.anydone.entities.User user = 3;</code>
     */
    private void setUser(
        com.treeleaf.anydone.entities.UserProto.User.Builder builderForValue) {
      user_ = builderForValue.build();
      
    }
    /**
     * <code>optional .treeleaf.anydone.entities.User user = 3;</code>
     */
    private void mergeUser(com.treeleaf.anydone.entities.UserProto.User value) {
      if (user_ != null &&
          user_ != com.treeleaf.anydone.entities.UserProto.User.getDefaultInstance()) {
        user_ =
          com.treeleaf.anydone.entities.UserProto.User.newBuilder(user_).mergeFrom(value).buildPartial();
      } else {
        user_ = value;
      }
      
    }
    /**
     * <code>optional .treeleaf.anydone.entities.User user = 3;</code>
     */
    private void clearUser() {  user_ = null;
      
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (role_ != com.treeleaf.anydone.entities.InboxProto.InboxParticipant.InboxRole.UNKNOWN_INBOX_ROLE.getNumber()) {
        output.writeEnum(1, role_);
      }
      if (!participantId_.isEmpty()) {
        output.writeString(2, getParticipantId());
      }
      if (user_ != null) {
        output.writeMessage(3, getUser());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (role_ != com.treeleaf.anydone.entities.InboxProto.InboxParticipant.InboxRole.UNKNOWN_INBOX_ROLE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, role_);
      }
      if (!participantId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getParticipantId());
      }
      if (user_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getUser());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.treeleaf.anydone.entities.InboxProto.InboxParticipant parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.treeleaf.anydone.entities.InboxProto.InboxParticipant parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.InboxProto.InboxParticipant parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.treeleaf.anydone.entities.InboxProto.InboxParticipant parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.InboxProto.InboxParticipant parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.anydone.entities.InboxProto.InboxParticipant parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.InboxProto.InboxParticipant parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.anydone.entities.InboxProto.InboxParticipant parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.InboxProto.InboxParticipant parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.anydone.entities.InboxProto.InboxParticipant parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.treeleaf.anydone.entities.InboxProto.InboxParticipant prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code treeleaf.anydone.entities.InboxParticipant}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.treeleaf.anydone.entities.InboxProto.InboxParticipant, Builder> implements
        // @@protoc_insertion_point(builder_implements:treeleaf.anydone.entities.InboxParticipant)
        com.treeleaf.anydone.entities.InboxProto.InboxParticipantOrBuilder {
      // Construct using com.treeleaf.anydone.entities.InboxProto.InboxParticipant.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional .treeleaf.anydone.entities.InboxParticipant.InboxRole role = 1;</code>
       */
      public int getRoleValue() {
        return instance.getRoleValue();
      }
      /**
       * <code>optional .treeleaf.anydone.entities.InboxParticipant.InboxRole role = 1;</code>
       */
      public Builder setRoleValue(int value) {
        copyOnWrite();
        instance.setRoleValue(value);
        return this;
      }
      /**
       * <code>optional .treeleaf.anydone.entities.InboxParticipant.InboxRole role = 1;</code>
       */
      public com.treeleaf.anydone.entities.InboxProto.InboxParticipant.InboxRole getRole() {
        return instance.getRole();
      }
      /**
       * <code>optional .treeleaf.anydone.entities.InboxParticipant.InboxRole role = 1;</code>
       */
      public Builder setRole(com.treeleaf.anydone.entities.InboxProto.InboxParticipant.InboxRole value) {
        copyOnWrite();
        instance.setRole(value);
        return this;
      }
      /**
       * <code>optional .treeleaf.anydone.entities.InboxParticipant.InboxRole role = 1;</code>
       */
      public Builder clearRole() {
        copyOnWrite();
        instance.clearRole();
        return this;
      }

      /**
       * <code>optional string participantId = 2;</code>
       */
      public java.lang.String getParticipantId() {
        return instance.getParticipantId();
      }
      /**
       * <code>optional string participantId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getParticipantIdBytes() {
        return instance.getParticipantIdBytes();
      }
      /**
       * <code>optional string participantId = 2;</code>
       */
      public Builder setParticipantId(
          java.lang.String value) {
        copyOnWrite();
        instance.setParticipantId(value);
        return this;
      }
      /**
       * <code>optional string participantId = 2;</code>
       */
      public Builder clearParticipantId() {
        copyOnWrite();
        instance.clearParticipantId();
        return this;
      }
      /**
       * <code>optional string participantId = 2;</code>
       */
      public Builder setParticipantIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setParticipantIdBytes(value);
        return this;
      }

      /**
       * <code>optional .treeleaf.anydone.entities.User user = 3;</code>
       */
      public boolean hasUser() {
        return instance.hasUser();
      }
      /**
       * <code>optional .treeleaf.anydone.entities.User user = 3;</code>
       */
      public com.treeleaf.anydone.entities.UserProto.User getUser() {
        return instance.getUser();
      }
      /**
       * <code>optional .treeleaf.anydone.entities.User user = 3;</code>
       */
      public Builder setUser(com.treeleaf.anydone.entities.UserProto.User value) {
        copyOnWrite();
        instance.setUser(value);
        return this;
        }
      /**
       * <code>optional .treeleaf.anydone.entities.User user = 3;</code>
       */
      public Builder setUser(
          com.treeleaf.anydone.entities.UserProto.User.Builder builderForValue) {
        copyOnWrite();
        instance.setUser(builderForValue);
        return this;
      }
      /**
       * <code>optional .treeleaf.anydone.entities.User user = 3;</code>
       */
      public Builder mergeUser(com.treeleaf.anydone.entities.UserProto.User value) {
        copyOnWrite();
        instance.mergeUser(value);
        return this;
      }
      /**
       * <code>optional .treeleaf.anydone.entities.User user = 3;</code>
       */
      public Builder clearUser() {  copyOnWrite();
        instance.clearUser();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:treeleaf.anydone.entities.InboxParticipant)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.treeleaf.anydone.entities.InboxProto.InboxParticipant();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.treeleaf.anydone.entities.InboxProto.InboxParticipant other = (com.treeleaf.anydone.entities.InboxProto.InboxParticipant) arg1;
          role_ = visitor.visitInt(role_ != 0, role_,    other.role_ != 0, other.role_);
          participantId_ = visitor.visitString(!participantId_.isEmpty(), participantId_,
              !other.participantId_.isEmpty(), other.participantId_);
          user_ = visitor.visitMessage(user_, other.user_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  int rawValue = input.readEnum();

                  role_ = rawValue;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  participantId_ = s;
                  break;
                }
                case 26: {
                  com.treeleaf.anydone.entities.UserProto.User.Builder subBuilder = null;
                  if (user_ != null) {
                    subBuilder = user_.toBuilder();
                  }
                  user_ = input.readMessage(com.treeleaf.anydone.entities.UserProto.User.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(user_);
                    user_ = subBuilder.buildPartial();
                  }

                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.treeleaf.anydone.entities.InboxProto.InboxParticipant.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:treeleaf.anydone.entities.InboxParticipant)
    private static final com.treeleaf.anydone.entities.InboxProto.InboxParticipant DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new InboxParticipant();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.treeleaf.anydone.entities.InboxProto.InboxParticipant getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<InboxParticipant> PARSER;

    public static com.google.protobuf.Parser<InboxParticipant> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface InboxOrBuilder extends
      // @@protoc_insertion_point(interface_extends:treeleaf.anydone.entities.Inbox)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional string serviceId = 2;</code>
     */
    java.lang.String getServiceId();
    /**
     * <code>optional string serviceId = 2;</code>
     */
    com.google.protobuf.ByteString
        getServiceIdBytes();

    /**
     * <code>optional string subject = 3;</code>
     */
    java.lang.String getSubject();
    /**
     * <code>optional string subject = 3;</code>
     */
    com.google.protobuf.ByteString
        getSubjectBytes();

    /**
     * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
     */
    java.util.List<com.treeleaf.anydone.entities.InboxProto.InboxParticipant> 
        getParticipantsList();
    /**
     * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
     */
    com.treeleaf.anydone.entities.InboxProto.InboxParticipant getParticipants(int index);
    /**
     * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
     */
    int getParticipantsCount();

    /**
     * <code>optional .treeleaf.anydone.entities.InboxParticipant createdBy = 5;</code>
     */
    boolean hasCreatedBy();
    /**
     * <code>optional .treeleaf.anydone.entities.InboxParticipant createdBy = 5;</code>
     */
    com.treeleaf.anydone.entities.InboxProto.InboxParticipant getCreatedBy();

    /**
     * <code>optional int64 createdAt = 6;</code>
     */
    long getCreatedAt();

    /**
     * <code>optional int64 updatedAt = 7;</code>
     */
    long getUpdatedAt();
  }
  /**
   * Protobuf type {@code treeleaf.anydone.entities.Inbox}
   */
  public  static final class Inbox extends
      com.google.protobuf.GeneratedMessageLite<
          Inbox, Inbox.Builder> implements
      // @@protoc_insertion_point(message_implements:treeleaf.anydone.entities.Inbox)
      InboxOrBuilder {
    private Inbox() {
      id_ = "";
      serviceId_ = "";
      subject_ = "";
      participants_ = emptyProtobufList();
    }
    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.String id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      return id_;
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(id_);
    }
    /**
     * <code>optional string id = 1;</code>
     */
    private void setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
    }
    /**
     * <code>optional string id = 1;</code>
     */
    private void clearId() {
      
      id_ = getDefaultInstance().getId();
    }
    /**
     * <code>optional string id = 1;</code>
     */
    private void setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value.toStringUtf8();
    }

    public static final int SERVICEID_FIELD_NUMBER = 2;
    private java.lang.String serviceId_;
    /**
     * <code>optional string serviceId = 2;</code>
     */
    public java.lang.String getServiceId() {
      return serviceId_;
    }
    /**
     * <code>optional string serviceId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getServiceIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(serviceId_);
    }
    /**
     * <code>optional string serviceId = 2;</code>
     */
    private void setServiceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serviceId_ = value;
    }
    /**
     * <code>optional string serviceId = 2;</code>
     */
    private void clearServiceId() {
      
      serviceId_ = getDefaultInstance().getServiceId();
    }
    /**
     * <code>optional string serviceId = 2;</code>
     */
    private void setServiceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serviceId_ = value.toStringUtf8();
    }

    public static final int SUBJECT_FIELD_NUMBER = 3;
    private java.lang.String subject_;
    /**
     * <code>optional string subject = 3;</code>
     */
    public java.lang.String getSubject() {
      return subject_;
    }
    /**
     * <code>optional string subject = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSubjectBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(subject_);
    }
    /**
     * <code>optional string subject = 3;</code>
     */
    private void setSubject(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      subject_ = value;
    }
    /**
     * <code>optional string subject = 3;</code>
     */
    private void clearSubject() {
      
      subject_ = getDefaultInstance().getSubject();
    }
    /**
     * <code>optional string subject = 3;</code>
     */
    private void setSubjectBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      subject_ = value.toStringUtf8();
    }

    public static final int PARTICIPANTS_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.ProtobufList<com.treeleaf.anydone.entities.InboxProto.InboxParticipant> participants_;
    /**
     * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
     */
    public java.util.List<com.treeleaf.anydone.entities.InboxProto.InboxParticipant> getParticipantsList() {
      return participants_;
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
     */
    public java.util.List<? extends com.treeleaf.anydone.entities.InboxProto.InboxParticipantOrBuilder> 
        getParticipantsOrBuilderList() {
      return participants_;
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
     */
    public int getParticipantsCount() {
      return participants_.size();
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
     */
    public com.treeleaf.anydone.entities.InboxProto.InboxParticipant getParticipants(int index) {
      return participants_.get(index);
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
     */
    public com.treeleaf.anydone.entities.InboxProto.InboxParticipantOrBuilder getParticipantsOrBuilder(
        int index) {
      return participants_.get(index);
    }
    private void ensureParticipantsIsMutable() {
      if (!participants_.isModifiable()) {
        participants_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(participants_);
       }
    }

    /**
     * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
     */
    private void setParticipants(
        int index, com.treeleaf.anydone.entities.InboxProto.InboxParticipant value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureParticipantsIsMutable();
      participants_.set(index, value);
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
     */
    private void setParticipants(
        int index, com.treeleaf.anydone.entities.InboxProto.InboxParticipant.Builder builderForValue) {
      ensureParticipantsIsMutable();
      participants_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
     */
    private void addParticipants(com.treeleaf.anydone.entities.InboxProto.InboxParticipant value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureParticipantsIsMutable();
      participants_.add(value);
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
     */
    private void addParticipants(
        int index, com.treeleaf.anydone.entities.InboxProto.InboxParticipant value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureParticipantsIsMutable();
      participants_.add(index, value);
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
     */
    private void addParticipants(
        com.treeleaf.anydone.entities.InboxProto.InboxParticipant.Builder builderForValue) {
      ensureParticipantsIsMutable();
      participants_.add(builderForValue.build());
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
     */
    private void addParticipants(
        int index, com.treeleaf.anydone.entities.InboxProto.InboxParticipant.Builder builderForValue) {
      ensureParticipantsIsMutable();
      participants_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
     */
    private void addAllParticipants(
        java.lang.Iterable<? extends com.treeleaf.anydone.entities.InboxProto.InboxParticipant> values) {
      ensureParticipantsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, participants_);
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
     */
    private void clearParticipants() {
      participants_ = emptyProtobufList();
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
     */
    private void removeParticipants(int index) {
      ensureParticipantsIsMutable();
      participants_.remove(index);
    }

    public static final int CREATEDBY_FIELD_NUMBER = 5;
    private com.treeleaf.anydone.entities.InboxProto.InboxParticipant createdBy_;
    /**
     * <code>optional .treeleaf.anydone.entities.InboxParticipant createdBy = 5;</code>
     */
    public boolean hasCreatedBy() {
      return createdBy_ != null;
    }
    /**
     * <code>optional .treeleaf.anydone.entities.InboxParticipant createdBy = 5;</code>
     */
    public com.treeleaf.anydone.entities.InboxProto.InboxParticipant getCreatedBy() {
      return createdBy_ == null ? com.treeleaf.anydone.entities.InboxProto.InboxParticipant.getDefaultInstance() : createdBy_;
    }
    /**
     * <code>optional .treeleaf.anydone.entities.InboxParticipant createdBy = 5;</code>
     */
    private void setCreatedBy(com.treeleaf.anydone.entities.InboxProto.InboxParticipant value) {
      if (value == null) {
        throw new NullPointerException();
      }
      createdBy_ = value;
      
      }
    /**
     * <code>optional .treeleaf.anydone.entities.InboxParticipant createdBy = 5;</code>
     */
    private void setCreatedBy(
        com.treeleaf.anydone.entities.InboxProto.InboxParticipant.Builder builderForValue) {
      createdBy_ = builderForValue.build();
      
    }
    /**
     * <code>optional .treeleaf.anydone.entities.InboxParticipant createdBy = 5;</code>
     */
    private void mergeCreatedBy(com.treeleaf.anydone.entities.InboxProto.InboxParticipant value) {
      if (createdBy_ != null &&
          createdBy_ != com.treeleaf.anydone.entities.InboxProto.InboxParticipant.getDefaultInstance()) {
        createdBy_ =
          com.treeleaf.anydone.entities.InboxProto.InboxParticipant.newBuilder(createdBy_).mergeFrom(value).buildPartial();
      } else {
        createdBy_ = value;
      }
      
    }
    /**
     * <code>optional .treeleaf.anydone.entities.InboxParticipant createdBy = 5;</code>
     */
    private void clearCreatedBy() {  createdBy_ = null;
      
    }

    public static final int CREATEDAT_FIELD_NUMBER = 6;
    private long createdAt_;
    /**
     * <code>optional int64 createdAt = 6;</code>
     */
    public long getCreatedAt() {
      return createdAt_;
    }
    /**
     * <code>optional int64 createdAt = 6;</code>
     */
    private void setCreatedAt(long value) {
      
      createdAt_ = value;
    }
    /**
     * <code>optional int64 createdAt = 6;</code>
     */
    private void clearCreatedAt() {
      
      createdAt_ = 0L;
    }

    public static final int UPDATEDAT_FIELD_NUMBER = 7;
    private long updatedAt_;
    /**
     * <code>optional int64 updatedAt = 7;</code>
     */
    public long getUpdatedAt() {
      return updatedAt_;
    }
    /**
     * <code>optional int64 updatedAt = 7;</code>
     */
    private void setUpdatedAt(long value) {
      
      updatedAt_ = value;
    }
    /**
     * <code>optional int64 updatedAt = 7;</code>
     */
    private void clearUpdatedAt() {
      
      updatedAt_ = 0L;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!id_.isEmpty()) {
        output.writeString(1, getId());
      }
      if (!serviceId_.isEmpty()) {
        output.writeString(2, getServiceId());
      }
      if (!subject_.isEmpty()) {
        output.writeString(3, getSubject());
      }
      for (int i = 0; i < participants_.size(); i++) {
        output.writeMessage(4, participants_.get(i));
      }
      if (createdBy_ != null) {
        output.writeMessage(5, getCreatedBy());
      }
      if (createdAt_ != 0L) {
        output.writeInt64(6, createdAt_);
      }
      if (updatedAt_ != 0L) {
        output.writeInt64(7, updatedAt_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!id_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getId());
      }
      if (!serviceId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getServiceId());
      }
      if (!subject_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getSubject());
      }
      for (int i = 0; i < participants_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, participants_.get(i));
      }
      if (createdBy_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getCreatedBy());
      }
      if (createdAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, createdAt_);
      }
      if (updatedAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, updatedAt_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.treeleaf.anydone.entities.InboxProto.Inbox parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.treeleaf.anydone.entities.InboxProto.Inbox parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.InboxProto.Inbox parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.treeleaf.anydone.entities.InboxProto.Inbox parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.InboxProto.Inbox parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.anydone.entities.InboxProto.Inbox parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.InboxProto.Inbox parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.anydone.entities.InboxProto.Inbox parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.InboxProto.Inbox parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.anydone.entities.InboxProto.Inbox parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.treeleaf.anydone.entities.InboxProto.Inbox prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code treeleaf.anydone.entities.Inbox}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.treeleaf.anydone.entities.InboxProto.Inbox, Builder> implements
        // @@protoc_insertion_point(builder_implements:treeleaf.anydone.entities.Inbox)
        com.treeleaf.anydone.entities.InboxProto.InboxOrBuilder {
      // Construct using com.treeleaf.anydone.entities.InboxProto.Inbox.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        return instance.getId();
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        return instance.getIdBytes();
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIdBytes(value);
        return this;
      }

      /**
       * <code>optional string serviceId = 2;</code>
       */
      public java.lang.String getServiceId() {
        return instance.getServiceId();
      }
      /**
       * <code>optional string serviceId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getServiceIdBytes() {
        return instance.getServiceIdBytes();
      }
      /**
       * <code>optional string serviceId = 2;</code>
       */
      public Builder setServiceId(
          java.lang.String value) {
        copyOnWrite();
        instance.setServiceId(value);
        return this;
      }
      /**
       * <code>optional string serviceId = 2;</code>
       */
      public Builder clearServiceId() {
        copyOnWrite();
        instance.clearServiceId();
        return this;
      }
      /**
       * <code>optional string serviceId = 2;</code>
       */
      public Builder setServiceIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setServiceIdBytes(value);
        return this;
      }

      /**
       * <code>optional string subject = 3;</code>
       */
      public java.lang.String getSubject() {
        return instance.getSubject();
      }
      /**
       * <code>optional string subject = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSubjectBytes() {
        return instance.getSubjectBytes();
      }
      /**
       * <code>optional string subject = 3;</code>
       */
      public Builder setSubject(
          java.lang.String value) {
        copyOnWrite();
        instance.setSubject(value);
        return this;
      }
      /**
       * <code>optional string subject = 3;</code>
       */
      public Builder clearSubject() {
        copyOnWrite();
        instance.clearSubject();
        return this;
      }
      /**
       * <code>optional string subject = 3;</code>
       */
      public Builder setSubjectBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSubjectBytes(value);
        return this;
      }

      /**
       * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
       */
      public java.util.List<com.treeleaf.anydone.entities.InboxProto.InboxParticipant> getParticipantsList() {
        return java.util.Collections.unmodifiableList(
            instance.getParticipantsList());
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
       */
      public int getParticipantsCount() {
        return instance.getParticipantsCount();
      }/**
       * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
       */
      public com.treeleaf.anydone.entities.InboxProto.InboxParticipant getParticipants(int index) {
        return instance.getParticipants(index);
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
       */
      public Builder setParticipants(
          int index, com.treeleaf.anydone.entities.InboxProto.InboxParticipant value) {
        copyOnWrite();
        instance.setParticipants(index, value);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
       */
      public Builder setParticipants(
          int index, com.treeleaf.anydone.entities.InboxProto.InboxParticipant.Builder builderForValue) {
        copyOnWrite();
        instance.setParticipants(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
       */
      public Builder addParticipants(com.treeleaf.anydone.entities.InboxProto.InboxParticipant value) {
        copyOnWrite();
        instance.addParticipants(value);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
       */
      public Builder addParticipants(
          int index, com.treeleaf.anydone.entities.InboxProto.InboxParticipant value) {
        copyOnWrite();
        instance.addParticipants(index, value);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
       */
      public Builder addParticipants(
          com.treeleaf.anydone.entities.InboxProto.InboxParticipant.Builder builderForValue) {
        copyOnWrite();
        instance.addParticipants(builderForValue);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
       */
      public Builder addParticipants(
          int index, com.treeleaf.anydone.entities.InboxProto.InboxParticipant.Builder builderForValue) {
        copyOnWrite();
        instance.addParticipants(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
       */
      public Builder addAllParticipants(
          java.lang.Iterable<? extends com.treeleaf.anydone.entities.InboxProto.InboxParticipant> values) {
        copyOnWrite();
        instance.addAllParticipants(values);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
       */
      public Builder clearParticipants() {
        copyOnWrite();
        instance.clearParticipants();
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.InboxParticipant participants = 4;</code>
       */
      public Builder removeParticipants(int index) {
        copyOnWrite();
        instance.removeParticipants(index);
        return this;
      }

      /**
       * <code>optional .treeleaf.anydone.entities.InboxParticipant createdBy = 5;</code>
       */
      public boolean hasCreatedBy() {
        return instance.hasCreatedBy();
      }
      /**
       * <code>optional .treeleaf.anydone.entities.InboxParticipant createdBy = 5;</code>
       */
      public com.treeleaf.anydone.entities.InboxProto.InboxParticipant getCreatedBy() {
        return instance.getCreatedBy();
      }
      /**
       * <code>optional .treeleaf.anydone.entities.InboxParticipant createdBy = 5;</code>
       */
      public Builder setCreatedBy(com.treeleaf.anydone.entities.InboxProto.InboxParticipant value) {
        copyOnWrite();
        instance.setCreatedBy(value);
        return this;
        }
      /**
       * <code>optional .treeleaf.anydone.entities.InboxParticipant createdBy = 5;</code>
       */
      public Builder setCreatedBy(
          com.treeleaf.anydone.entities.InboxProto.InboxParticipant.Builder builderForValue) {
        copyOnWrite();
        instance.setCreatedBy(builderForValue);
        return this;
      }
      /**
       * <code>optional .treeleaf.anydone.entities.InboxParticipant createdBy = 5;</code>
       */
      public Builder mergeCreatedBy(com.treeleaf.anydone.entities.InboxProto.InboxParticipant value) {
        copyOnWrite();
        instance.mergeCreatedBy(value);
        return this;
      }
      /**
       * <code>optional .treeleaf.anydone.entities.InboxParticipant createdBy = 5;</code>
       */
      public Builder clearCreatedBy() {  copyOnWrite();
        instance.clearCreatedBy();
        return this;
      }

      /**
       * <code>optional int64 createdAt = 6;</code>
       */
      public long getCreatedAt() {
        return instance.getCreatedAt();
      }
      /**
       * <code>optional int64 createdAt = 6;</code>
       */
      public Builder setCreatedAt(long value) {
        copyOnWrite();
        instance.setCreatedAt(value);
        return this;
      }
      /**
       * <code>optional int64 createdAt = 6;</code>
       */
      public Builder clearCreatedAt() {
        copyOnWrite();
        instance.clearCreatedAt();
        return this;
      }

      /**
       * <code>optional int64 updatedAt = 7;</code>
       */
      public long getUpdatedAt() {
        return instance.getUpdatedAt();
      }
      /**
       * <code>optional int64 updatedAt = 7;</code>
       */
      public Builder setUpdatedAt(long value) {
        copyOnWrite();
        instance.setUpdatedAt(value);
        return this;
      }
      /**
       * <code>optional int64 updatedAt = 7;</code>
       */
      public Builder clearUpdatedAt() {
        copyOnWrite();
        instance.clearUpdatedAt();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:treeleaf.anydone.entities.Inbox)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.treeleaf.anydone.entities.InboxProto.Inbox();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          participants_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.treeleaf.anydone.entities.InboxProto.Inbox other = (com.treeleaf.anydone.entities.InboxProto.Inbox) arg1;
          id_ = visitor.visitString(!id_.isEmpty(), id_,
              !other.id_.isEmpty(), other.id_);
          serviceId_ = visitor.visitString(!serviceId_.isEmpty(), serviceId_,
              !other.serviceId_.isEmpty(), other.serviceId_);
          subject_ = visitor.visitString(!subject_.isEmpty(), subject_,
              !other.subject_.isEmpty(), other.subject_);
          participants_= visitor.visitList(participants_, other.participants_);
          createdBy_ = visitor.visitMessage(createdBy_, other.createdBy_);
          createdAt_ = visitor.visitLong(createdAt_ != 0L, createdAt_,
              other.createdAt_ != 0L, other.createdAt_);
          updatedAt_ = visitor.visitLong(updatedAt_ != 0L, updatedAt_,
              other.updatedAt_ != 0L, other.updatedAt_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  id_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  serviceId_ = s;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  subject_ = s;
                  break;
                }
                case 34: {
                  if (!participants_.isModifiable()) {
                    participants_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(participants_);
                  }
                  participants_.add(
                      input.readMessage(com.treeleaf.anydone.entities.InboxProto.InboxParticipant.parser(), extensionRegistry));
                  break;
                }
                case 42: {
                  com.treeleaf.anydone.entities.InboxProto.InboxParticipant.Builder subBuilder = null;
                  if (createdBy_ != null) {
                    subBuilder = createdBy_.toBuilder();
                  }
                  createdBy_ = input.readMessage(com.treeleaf.anydone.entities.InboxProto.InboxParticipant.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(createdBy_);
                    createdBy_ = subBuilder.buildPartial();
                  }

                  break;
                }
                case 48: {

                  createdAt_ = input.readInt64();
                  break;
                }
                case 56: {

                  updatedAt_ = input.readInt64();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.treeleaf.anydone.entities.InboxProto.Inbox.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:treeleaf.anydone.entities.Inbox)
    private static final com.treeleaf.anydone.entities.InboxProto.Inbox DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Inbox();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.treeleaf.anydone.entities.InboxProto.Inbox getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Inbox> PARSER;

    public static com.google.protobuf.Parser<Inbox> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface InboxFilterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:treeleaf.anydone.entities.InboxFilter)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string serviceId = 1;</code>
     */
    java.lang.String getServiceId();
    /**
     * <code>optional string serviceId = 1;</code>
     */
    com.google.protobuf.ByteString
        getServiceIdBytes();

    /**
     * <code>optional string query = 2;</code>
     */
    java.lang.String getQuery();
    /**
     * <code>optional string query = 2;</code>
     */
    com.google.protobuf.ByteString
        getQueryBytes();

    /**
     * <code>optional .treeleaf.protos.DataQuery dataQuery = 3;</code>
     */
    boolean hasDataQuery();
    /**
     * <code>optional .treeleaf.protos.DataQuery dataQuery = 3;</code>
     */
    com.treeleaf.anydone.entities.TreeleafProto.DataQuery getDataQuery();
  }
  /**
   * Protobuf type {@code treeleaf.anydone.entities.InboxFilter}
   */
  public  static final class InboxFilter extends
      com.google.protobuf.GeneratedMessageLite<
          InboxFilter, InboxFilter.Builder> implements
      // @@protoc_insertion_point(message_implements:treeleaf.anydone.entities.InboxFilter)
      InboxFilterOrBuilder {
    private InboxFilter() {
      serviceId_ = "";
      query_ = "";
    }
    public static final int SERVICEID_FIELD_NUMBER = 1;
    private java.lang.String serviceId_;
    /**
     * <code>optional string serviceId = 1;</code>
     */
    public java.lang.String getServiceId() {
      return serviceId_;
    }
    /**
     * <code>optional string serviceId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServiceIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(serviceId_);
    }
    /**
     * <code>optional string serviceId = 1;</code>
     */
    private void setServiceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serviceId_ = value;
    }
    /**
     * <code>optional string serviceId = 1;</code>
     */
    private void clearServiceId() {
      
      serviceId_ = getDefaultInstance().getServiceId();
    }
    /**
     * <code>optional string serviceId = 1;</code>
     */
    private void setServiceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serviceId_ = value.toStringUtf8();
    }

    public static final int QUERY_FIELD_NUMBER = 2;
    private java.lang.String query_;
    /**
     * <code>optional string query = 2;</code>
     */
    public java.lang.String getQuery() {
      return query_;
    }
    /**
     * <code>optional string query = 2;</code>
     */
    public com.google.protobuf.ByteString
        getQueryBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(query_);
    }
    /**
     * <code>optional string query = 2;</code>
     */
    private void setQuery(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      query_ = value;
    }
    /**
     * <code>optional string query = 2;</code>
     */
    private void clearQuery() {
      
      query_ = getDefaultInstance().getQuery();
    }
    /**
     * <code>optional string query = 2;</code>
     */
    private void setQueryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      query_ = value.toStringUtf8();
    }

    public static final int DATAQUERY_FIELD_NUMBER = 3;
    private com.treeleaf.anydone.entities.TreeleafProto.DataQuery dataQuery_;
    /**
     * <code>optional .treeleaf.protos.DataQuery dataQuery = 3;</code>
     */
    public boolean hasDataQuery() {
      return dataQuery_ != null;
    }
    /**
     * <code>optional .treeleaf.protos.DataQuery dataQuery = 3;</code>
     */
    public com.treeleaf.anydone.entities.TreeleafProto.DataQuery getDataQuery() {
      return dataQuery_ == null ? com.treeleaf.anydone.entities.TreeleafProto.DataQuery.getDefaultInstance() : dataQuery_;
    }
    /**
     * <code>optional .treeleaf.protos.DataQuery dataQuery = 3;</code>
     */
    private void setDataQuery(com.treeleaf.anydone.entities.TreeleafProto.DataQuery value) {
      if (value == null) {
        throw new NullPointerException();
      }
      dataQuery_ = value;
      
      }
    /**
     * <code>optional .treeleaf.protos.DataQuery dataQuery = 3;</code>
     */
    private void setDataQuery(
        com.treeleaf.anydone.entities.TreeleafProto.DataQuery.Builder builderForValue) {
      dataQuery_ = builderForValue.build();
      
    }
    /**
     * <code>optional .treeleaf.protos.DataQuery dataQuery = 3;</code>
     */
    private void mergeDataQuery(com.treeleaf.anydone.entities.TreeleafProto.DataQuery value) {
      if (dataQuery_ != null &&
          dataQuery_ != com.treeleaf.anydone.entities.TreeleafProto.DataQuery.getDefaultInstance()) {
        dataQuery_ =
          com.treeleaf.anydone.entities.TreeleafProto.DataQuery.newBuilder(dataQuery_).mergeFrom(value).buildPartial();
      } else {
        dataQuery_ = value;
      }
      
    }
    /**
     * <code>optional .treeleaf.protos.DataQuery dataQuery = 3;</code>
     */
    private void clearDataQuery() {  dataQuery_ = null;
      
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!serviceId_.isEmpty()) {
        output.writeString(1, getServiceId());
      }
      if (!query_.isEmpty()) {
        output.writeString(2, getQuery());
      }
      if (dataQuery_ != null) {
        output.writeMessage(3, getDataQuery());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!serviceId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getServiceId());
      }
      if (!query_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getQuery());
      }
      if (dataQuery_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getDataQuery());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.treeleaf.anydone.entities.InboxProto.InboxFilter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.treeleaf.anydone.entities.InboxProto.InboxFilter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.InboxProto.InboxFilter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.treeleaf.anydone.entities.InboxProto.InboxFilter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.InboxProto.InboxFilter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.anydone.entities.InboxProto.InboxFilter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.InboxProto.InboxFilter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.anydone.entities.InboxProto.InboxFilter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.InboxProto.InboxFilter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.anydone.entities.InboxProto.InboxFilter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.treeleaf.anydone.entities.InboxProto.InboxFilter prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code treeleaf.anydone.entities.InboxFilter}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.treeleaf.anydone.entities.InboxProto.InboxFilter, Builder> implements
        // @@protoc_insertion_point(builder_implements:treeleaf.anydone.entities.InboxFilter)
        com.treeleaf.anydone.entities.InboxProto.InboxFilterOrBuilder {
      // Construct using com.treeleaf.anydone.entities.InboxProto.InboxFilter.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string serviceId = 1;</code>
       */
      public java.lang.String getServiceId() {
        return instance.getServiceId();
      }
      /**
       * <code>optional string serviceId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServiceIdBytes() {
        return instance.getServiceIdBytes();
      }
      /**
       * <code>optional string serviceId = 1;</code>
       */
      public Builder setServiceId(
          java.lang.String value) {
        copyOnWrite();
        instance.setServiceId(value);
        return this;
      }
      /**
       * <code>optional string serviceId = 1;</code>
       */
      public Builder clearServiceId() {
        copyOnWrite();
        instance.clearServiceId();
        return this;
      }
      /**
       * <code>optional string serviceId = 1;</code>
       */
      public Builder setServiceIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setServiceIdBytes(value);
        return this;
      }

      /**
       * <code>optional string query = 2;</code>
       */
      public java.lang.String getQuery() {
        return instance.getQuery();
      }
      /**
       * <code>optional string query = 2;</code>
       */
      public com.google.protobuf.ByteString
          getQueryBytes() {
        return instance.getQueryBytes();
      }
      /**
       * <code>optional string query = 2;</code>
       */
      public Builder setQuery(
          java.lang.String value) {
        copyOnWrite();
        instance.setQuery(value);
        return this;
      }
      /**
       * <code>optional string query = 2;</code>
       */
      public Builder clearQuery() {
        copyOnWrite();
        instance.clearQuery();
        return this;
      }
      /**
       * <code>optional string query = 2;</code>
       */
      public Builder setQueryBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setQueryBytes(value);
        return this;
      }

      /**
       * <code>optional .treeleaf.protos.DataQuery dataQuery = 3;</code>
       */
      public boolean hasDataQuery() {
        return instance.hasDataQuery();
      }
      /**
       * <code>optional .treeleaf.protos.DataQuery dataQuery = 3;</code>
       */
      public com.treeleaf.anydone.entities.TreeleafProto.DataQuery getDataQuery() {
        return instance.getDataQuery();
      }
      /**
       * <code>optional .treeleaf.protos.DataQuery dataQuery = 3;</code>
       */
      public Builder setDataQuery(com.treeleaf.anydone.entities.TreeleafProto.DataQuery value) {
        copyOnWrite();
        instance.setDataQuery(value);
        return this;
        }
      /**
       * <code>optional .treeleaf.protos.DataQuery dataQuery = 3;</code>
       */
      public Builder setDataQuery(
          com.treeleaf.anydone.entities.TreeleafProto.DataQuery.Builder builderForValue) {
        copyOnWrite();
        instance.setDataQuery(builderForValue);
        return this;
      }
      /**
       * <code>optional .treeleaf.protos.DataQuery dataQuery = 3;</code>
       */
      public Builder mergeDataQuery(com.treeleaf.anydone.entities.TreeleafProto.DataQuery value) {
        copyOnWrite();
        instance.mergeDataQuery(value);
        return this;
      }
      /**
       * <code>optional .treeleaf.protos.DataQuery dataQuery = 3;</code>
       */
      public Builder clearDataQuery() {  copyOnWrite();
        instance.clearDataQuery();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:treeleaf.anydone.entities.InboxFilter)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.treeleaf.anydone.entities.InboxProto.InboxFilter();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.treeleaf.anydone.entities.InboxProto.InboxFilter other = (com.treeleaf.anydone.entities.InboxProto.InboxFilter) arg1;
          serviceId_ = visitor.visitString(!serviceId_.isEmpty(), serviceId_,
              !other.serviceId_.isEmpty(), other.serviceId_);
          query_ = visitor.visitString(!query_.isEmpty(), query_,
              !other.query_.isEmpty(), other.query_);
          dataQuery_ = visitor.visitMessage(dataQuery_, other.dataQuery_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  serviceId_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  query_ = s;
                  break;
                }
                case 26: {
                  com.treeleaf.anydone.entities.TreeleafProto.DataQuery.Builder subBuilder = null;
                  if (dataQuery_ != null) {
                    subBuilder = dataQuery_.toBuilder();
                  }
                  dataQuery_ = input.readMessage(com.treeleaf.anydone.entities.TreeleafProto.DataQuery.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(dataQuery_);
                    dataQuery_ = subBuilder.buildPartial();
                  }

                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.treeleaf.anydone.entities.InboxProto.InboxFilter.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:treeleaf.anydone.entities.InboxFilter)
    private static final com.treeleaf.anydone.entities.InboxProto.InboxFilter DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new InboxFilter();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.treeleaf.anydone.entities.InboxProto.InboxFilter getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<InboxFilter> PARSER;

    public static com.google.protobuf.Parser<InboxFilter> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface InboxResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:treeleaf.anydone.entities.InboxResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
     */
    java.util.List<com.treeleaf.anydone.entities.InboxProto.Inbox> 
        getInboxList();
    /**
     * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
     */
    com.treeleaf.anydone.entities.InboxProto.Inbox getInbox(int index);
    /**
     * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
     */
    int getInboxCount();

    /**
     * <code>optional int64 count = 2;</code>
     */
    long getCount();
  }
  /**
   * Protobuf type {@code treeleaf.anydone.entities.InboxResponse}
   */
  public  static final class InboxResponse extends
      com.google.protobuf.GeneratedMessageLite<
          InboxResponse, InboxResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:treeleaf.anydone.entities.InboxResponse)
      InboxResponseOrBuilder {
    private InboxResponse() {
      inbox_ = emptyProtobufList();
    }
    private int bitField0_;
    public static final int INBOX_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.treeleaf.anydone.entities.InboxProto.Inbox> inbox_;
    /**
     * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
     */
    public java.util.List<com.treeleaf.anydone.entities.InboxProto.Inbox> getInboxList() {
      return inbox_;
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
     */
    public java.util.List<? extends com.treeleaf.anydone.entities.InboxProto.InboxOrBuilder> 
        getInboxOrBuilderList() {
      return inbox_;
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
     */
    public int getInboxCount() {
      return inbox_.size();
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
     */
    public com.treeleaf.anydone.entities.InboxProto.Inbox getInbox(int index) {
      return inbox_.get(index);
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
     */
    public com.treeleaf.anydone.entities.InboxProto.InboxOrBuilder getInboxOrBuilder(
        int index) {
      return inbox_.get(index);
    }
    private void ensureInboxIsMutable() {
      if (!inbox_.isModifiable()) {
        inbox_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(inbox_);
       }
    }

    /**
     * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
     */
    private void setInbox(
        int index, com.treeleaf.anydone.entities.InboxProto.Inbox value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureInboxIsMutable();
      inbox_.set(index, value);
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
     */
    private void setInbox(
        int index, com.treeleaf.anydone.entities.InboxProto.Inbox.Builder builderForValue) {
      ensureInboxIsMutable();
      inbox_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
     */
    private void addInbox(com.treeleaf.anydone.entities.InboxProto.Inbox value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureInboxIsMutable();
      inbox_.add(value);
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
     */
    private void addInbox(
        int index, com.treeleaf.anydone.entities.InboxProto.Inbox value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureInboxIsMutable();
      inbox_.add(index, value);
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
     */
    private void addInbox(
        com.treeleaf.anydone.entities.InboxProto.Inbox.Builder builderForValue) {
      ensureInboxIsMutable();
      inbox_.add(builderForValue.build());
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
     */
    private void addInbox(
        int index, com.treeleaf.anydone.entities.InboxProto.Inbox.Builder builderForValue) {
      ensureInboxIsMutable();
      inbox_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
     */
    private void addAllInbox(
        java.lang.Iterable<? extends com.treeleaf.anydone.entities.InboxProto.Inbox> values) {
      ensureInboxIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, inbox_);
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
     */
    private void clearInbox() {
      inbox_ = emptyProtobufList();
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
     */
    private void removeInbox(int index) {
      ensureInboxIsMutable();
      inbox_.remove(index);
    }

    public static final int COUNT_FIELD_NUMBER = 2;
    private long count_;
    /**
     * <code>optional int64 count = 2;</code>
     */
    public long getCount() {
      return count_;
    }
    /**
     * <code>optional int64 count = 2;</code>
     */
    private void setCount(long value) {
      
      count_ = value;
    }
    /**
     * <code>optional int64 count = 2;</code>
     */
    private void clearCount() {
      
      count_ = 0L;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < inbox_.size(); i++) {
        output.writeMessage(1, inbox_.get(i));
      }
      if (count_ != 0L) {
        output.writeInt64(2, count_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < inbox_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, inbox_.get(i));
      }
      if (count_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, count_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.treeleaf.anydone.entities.InboxProto.InboxResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.treeleaf.anydone.entities.InboxProto.InboxResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.InboxProto.InboxResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.treeleaf.anydone.entities.InboxProto.InboxResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.InboxProto.InboxResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.anydone.entities.InboxProto.InboxResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.InboxProto.InboxResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.anydone.entities.InboxProto.InboxResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.treeleaf.anydone.entities.InboxProto.InboxResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.treeleaf.anydone.entities.InboxProto.InboxResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.treeleaf.anydone.entities.InboxProto.InboxResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code treeleaf.anydone.entities.InboxResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.treeleaf.anydone.entities.InboxProto.InboxResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:treeleaf.anydone.entities.InboxResponse)
        com.treeleaf.anydone.entities.InboxProto.InboxResponseOrBuilder {
      // Construct using com.treeleaf.anydone.entities.InboxProto.InboxResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
       */
      public java.util.List<com.treeleaf.anydone.entities.InboxProto.Inbox> getInboxList() {
        return java.util.Collections.unmodifiableList(
            instance.getInboxList());
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
       */
      public int getInboxCount() {
        return instance.getInboxCount();
      }/**
       * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
       */
      public com.treeleaf.anydone.entities.InboxProto.Inbox getInbox(int index) {
        return instance.getInbox(index);
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
       */
      public Builder setInbox(
          int index, com.treeleaf.anydone.entities.InboxProto.Inbox value) {
        copyOnWrite();
        instance.setInbox(index, value);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
       */
      public Builder setInbox(
          int index, com.treeleaf.anydone.entities.InboxProto.Inbox.Builder builderForValue) {
        copyOnWrite();
        instance.setInbox(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
       */
      public Builder addInbox(com.treeleaf.anydone.entities.InboxProto.Inbox value) {
        copyOnWrite();
        instance.addInbox(value);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
       */
      public Builder addInbox(
          int index, com.treeleaf.anydone.entities.InboxProto.Inbox value) {
        copyOnWrite();
        instance.addInbox(index, value);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
       */
      public Builder addInbox(
          com.treeleaf.anydone.entities.InboxProto.Inbox.Builder builderForValue) {
        copyOnWrite();
        instance.addInbox(builderForValue);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
       */
      public Builder addInbox(
          int index, com.treeleaf.anydone.entities.InboxProto.Inbox.Builder builderForValue) {
        copyOnWrite();
        instance.addInbox(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
       */
      public Builder addAllInbox(
          java.lang.Iterable<? extends com.treeleaf.anydone.entities.InboxProto.Inbox> values) {
        copyOnWrite();
        instance.addAllInbox(values);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
       */
      public Builder clearInbox() {
        copyOnWrite();
        instance.clearInbox();
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.Inbox inbox = 1;</code>
       */
      public Builder removeInbox(int index) {
        copyOnWrite();
        instance.removeInbox(index);
        return this;
      }

      /**
       * <code>optional int64 count = 2;</code>
       */
      public long getCount() {
        return instance.getCount();
      }
      /**
       * <code>optional int64 count = 2;</code>
       */
      public Builder setCount(long value) {
        copyOnWrite();
        instance.setCount(value);
        return this;
      }
      /**
       * <code>optional int64 count = 2;</code>
       */
      public Builder clearCount() {
        copyOnWrite();
        instance.clearCount();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:treeleaf.anydone.entities.InboxResponse)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.treeleaf.anydone.entities.InboxProto.InboxResponse();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          inbox_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.treeleaf.anydone.entities.InboxProto.InboxResponse other = (com.treeleaf.anydone.entities.InboxProto.InboxResponse) arg1;
          inbox_= visitor.visitList(inbox_, other.inbox_);
          count_ = visitor.visitLong(count_ != 0L, count_,
              other.count_ != 0L, other.count_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!inbox_.isModifiable()) {
                    inbox_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(inbox_);
                  }
                  inbox_.add(
                      input.readMessage(com.treeleaf.anydone.entities.InboxProto.Inbox.parser(), extensionRegistry));
                  break;
                }
                case 16: {

                  count_ = input.readInt64();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.treeleaf.anydone.entities.InboxProto.InboxResponse.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:treeleaf.anydone.entities.InboxResponse)
    private static final com.treeleaf.anydone.entities.InboxProto.InboxResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new InboxResponse();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.treeleaf.anydone.entities.InboxProto.InboxResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<InboxResponse> PARSER;

    public static com.google.protobuf.Parser<InboxResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
