// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: integration.proto

package com.treeleaf.anydone.entities;

public final class IntegrationProto {
  private IntegrationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface IntegrationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:treeleaf.anydone.entities.Integration)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string integrationId = 1;</code>
     */
    String getIntegrationId();
    /**
     * <code>optional string integrationId = 1;</code>
     */
    com.google.protobuf.ByteString
        getIntegrationIdBytes();

    /**
     * <code>optional .treeleaf.anydone.entities.IntegrationMessenger integrationMessenger = 2;</code>
     */
    boolean hasIntegrationMessenger();
    /**
     * <code>optional .treeleaf.anydone.entities.IntegrationMessenger integrationMessenger = 2;</code>
     */
    IntegrationMessenger getIntegrationMessenger();

    /**
     * <code>optional string serviceProviderAccountId = 3;</code>
     */
    String getServiceProviderAccountId();
    /**
     * <code>optional string serviceProviderAccountId = 3;</code>
     */
    com.google.protobuf.ByteString
        getServiceProviderAccountIdBytes();

    /**
     * <code>optional string defaultLabelId = 4;</code>
     */
    String getDefaultLabelId();
    /**
     * <code>optional string defaultLabelId = 4;</code>
     */
    com.google.protobuf.ByteString
        getDefaultLabelIdBytes();

    /**
     * <code>optional string serviceId = 5;</code>
     */
    String getServiceId();
    /**
     * <code>optional string serviceId = 5;</code>
     */
    com.google.protobuf.ByteString
        getServiceIdBytes();

    /**
     * <code>optional .treeleaf.anydone.entities.ThirdPartySource source = 6;</code>
     */
    int getSourceValue();
    /**
     * <code>optional .treeleaf.anydone.entities.ThirdPartySource source = 6;</code>
     */
    UserProto.ThirdPartySource getSource();

    /**
     * <code>optional bool isEnabled = 7;</code>
     */
    boolean getIsEnabled();

    /**
     * <code>optional int64 createdAt = 8;</code>
     */
    long getCreatedAt();

    /**
     * <code>optional int64 updatedAt = 9;</code>
     */
    long getUpdatedAt();
  }
  /**
   * Protobuf type {@code treeleaf.anydone.entities.Integration}
   */
  public  static final class Integration extends
      com.google.protobuf.GeneratedMessageLite<
          Integration, Integration.Builder> implements
      // @@protoc_insertion_point(message_implements:treeleaf.anydone.entities.Integration)
      IntegrationOrBuilder {
    private Integration() {
      integrationId_ = "";
      serviceProviderAccountId_ = "";
      defaultLabelId_ = "";
      serviceId_ = "";
    }
    public static final int INTEGRATIONID_FIELD_NUMBER = 1;
    private String integrationId_;
    /**
     * <code>optional string integrationId = 1;</code>
     */
    public String getIntegrationId() {
      return integrationId_;
    }
    /**
     * <code>optional string integrationId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIntegrationIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(integrationId_);
    }
    /**
     * <code>optional string integrationId = 1;</code>
     */
    private void setIntegrationId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      integrationId_ = value;
    }
    /**
     * <code>optional string integrationId = 1;</code>
     */
    private void clearIntegrationId() {
      
      integrationId_ = getDefaultInstance().getIntegrationId();
    }
    /**
     * <code>optional string integrationId = 1;</code>
     */
    private void setIntegrationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      integrationId_ = value.toStringUtf8();
    }

    public static final int INTEGRATIONMESSENGER_FIELD_NUMBER = 2;
    private IntegrationMessenger integrationMessenger_;
    /**
     * <code>optional .treeleaf.anydone.entities.IntegrationMessenger integrationMessenger = 2;</code>
     */
    public boolean hasIntegrationMessenger() {
      return integrationMessenger_ != null;
    }
    /**
     * <code>optional .treeleaf.anydone.entities.IntegrationMessenger integrationMessenger = 2;</code>
     */
    public IntegrationMessenger getIntegrationMessenger() {
      return integrationMessenger_ == null ? IntegrationMessenger.getDefaultInstance() : integrationMessenger_;
    }
    /**
     * <code>optional .treeleaf.anydone.entities.IntegrationMessenger integrationMessenger = 2;</code>
     */
    private void setIntegrationMessenger(IntegrationMessenger value) {
      if (value == null) {
        throw new NullPointerException();
      }
      integrationMessenger_ = value;
      
      }
    /**
     * <code>optional .treeleaf.anydone.entities.IntegrationMessenger integrationMessenger = 2;</code>
     */
    private void setIntegrationMessenger(
        IntegrationMessenger.Builder builderForValue) {
      integrationMessenger_ = builderForValue.build();
      
    }
    /**
     * <code>optional .treeleaf.anydone.entities.IntegrationMessenger integrationMessenger = 2;</code>
     */
    private void mergeIntegrationMessenger(IntegrationMessenger value) {
      if (integrationMessenger_ != null &&
          integrationMessenger_ != IntegrationMessenger.getDefaultInstance()) {
        integrationMessenger_ =
          IntegrationMessenger.newBuilder(integrationMessenger_).mergeFrom(value).buildPartial();
      } else {
        integrationMessenger_ = value;
      }
      
    }
    /**
     * <code>optional .treeleaf.anydone.entities.IntegrationMessenger integrationMessenger = 2;</code>
     */
    private void clearIntegrationMessenger() {  integrationMessenger_ = null;
      
    }

    public static final int SERVICEPROVIDERACCOUNTID_FIELD_NUMBER = 3;
    private String serviceProviderAccountId_;
    /**
     * <code>optional string serviceProviderAccountId = 3;</code>
     */
    public String getServiceProviderAccountId() {
      return serviceProviderAccountId_;
    }
    /**
     * <code>optional string serviceProviderAccountId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getServiceProviderAccountIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(serviceProviderAccountId_);
    }
    /**
     * <code>optional string serviceProviderAccountId = 3;</code>
     */
    private void setServiceProviderAccountId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serviceProviderAccountId_ = value;
    }
    /**
     * <code>optional string serviceProviderAccountId = 3;</code>
     */
    private void clearServiceProviderAccountId() {
      
      serviceProviderAccountId_ = getDefaultInstance().getServiceProviderAccountId();
    }
    /**
     * <code>optional string serviceProviderAccountId = 3;</code>
     */
    private void setServiceProviderAccountIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serviceProviderAccountId_ = value.toStringUtf8();
    }

    public static final int DEFAULTLABELID_FIELD_NUMBER = 4;
    private String defaultLabelId_;
    /**
     * <code>optional string defaultLabelId = 4;</code>
     */
    public String getDefaultLabelId() {
      return defaultLabelId_;
    }
    /**
     * <code>optional string defaultLabelId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDefaultLabelIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(defaultLabelId_);
    }
    /**
     * <code>optional string defaultLabelId = 4;</code>
     */
    private void setDefaultLabelId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      defaultLabelId_ = value;
    }
    /**
     * <code>optional string defaultLabelId = 4;</code>
     */
    private void clearDefaultLabelId() {
      
      defaultLabelId_ = getDefaultInstance().getDefaultLabelId();
    }
    /**
     * <code>optional string defaultLabelId = 4;</code>
     */
    private void setDefaultLabelIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      defaultLabelId_ = value.toStringUtf8();
    }

    public static final int SERVICEID_FIELD_NUMBER = 5;
    private String serviceId_;
    /**
     * <code>optional string serviceId = 5;</code>
     */
    public String getServiceId() {
      return serviceId_;
    }
    /**
     * <code>optional string serviceId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getServiceIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(serviceId_);
    }
    /**
     * <code>optional string serviceId = 5;</code>
     */
    private void setServiceId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serviceId_ = value;
    }
    /**
     * <code>optional string serviceId = 5;</code>
     */
    private void clearServiceId() {
      
      serviceId_ = getDefaultInstance().getServiceId();
    }
    /**
     * <code>optional string serviceId = 5;</code>
     */
    private void setServiceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serviceId_ = value.toStringUtf8();
    }

    public static final int SOURCE_FIELD_NUMBER = 6;
    private int source_;
    /**
     * <code>optional .treeleaf.anydone.entities.ThirdPartySource source = 6;</code>
     */
    public int getSourceValue() {
      return source_;
    }
    /**
     * <code>optional .treeleaf.anydone.entities.ThirdPartySource source = 6;</code>
     */
    public UserProto.ThirdPartySource getSource() {
      UserProto.ThirdPartySource result = UserProto.ThirdPartySource.forNumber(source_);
      return result == null ? UserProto.ThirdPartySource.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .treeleaf.anydone.entities.ThirdPartySource source = 6;</code>
     */
    private void setSourceValue(int value) {
        source_ = value;
    }
    /**
     * <code>optional .treeleaf.anydone.entities.ThirdPartySource source = 6;</code>
     */
    private void setSource(UserProto.ThirdPartySource value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      source_ = value.getNumber();
    }
    /**
     * <code>optional .treeleaf.anydone.entities.ThirdPartySource source = 6;</code>
     */
    private void clearSource() {
      
      source_ = 0;
    }

    public static final int ISENABLED_FIELD_NUMBER = 7;
    private boolean isEnabled_;
    /**
     * <code>optional bool isEnabled = 7;</code>
     */
    public boolean getIsEnabled() {
      return isEnabled_;
    }
    /**
     * <code>optional bool isEnabled = 7;</code>
     */
    private void setIsEnabled(boolean value) {
      
      isEnabled_ = value;
    }
    /**
     * <code>optional bool isEnabled = 7;</code>
     */
    private void clearIsEnabled() {
      
      isEnabled_ = false;
    }

    public static final int CREATEDAT_FIELD_NUMBER = 8;
    private long createdAt_;
    /**
     * <code>optional int64 createdAt = 8;</code>
     */
    public long getCreatedAt() {
      return createdAt_;
    }
    /**
     * <code>optional int64 createdAt = 8;</code>
     */
    private void setCreatedAt(long value) {
      
      createdAt_ = value;
    }
    /**
     * <code>optional int64 createdAt = 8;</code>
     */
    private void clearCreatedAt() {
      
      createdAt_ = 0L;
    }

    public static final int UPDATEDAT_FIELD_NUMBER = 9;
    private long updatedAt_;
    /**
     * <code>optional int64 updatedAt = 9;</code>
     */
    public long getUpdatedAt() {
      return updatedAt_;
    }
    /**
     * <code>optional int64 updatedAt = 9;</code>
     */
    private void setUpdatedAt(long value) {
      
      updatedAt_ = value;
    }
    /**
     * <code>optional int64 updatedAt = 9;</code>
     */
    private void clearUpdatedAt() {
      
      updatedAt_ = 0L;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!integrationId_.isEmpty()) {
        output.writeString(1, getIntegrationId());
      }
      if (integrationMessenger_ != null) {
        output.writeMessage(2, getIntegrationMessenger());
      }
      if (!serviceProviderAccountId_.isEmpty()) {
        output.writeString(3, getServiceProviderAccountId());
      }
      if (!defaultLabelId_.isEmpty()) {
        output.writeString(4, getDefaultLabelId());
      }
      if (!serviceId_.isEmpty()) {
        output.writeString(5, getServiceId());
      }
      if (source_ != UserProto.ThirdPartySource.UNKNOWN_THIRD_PARTY_SOURCE.getNumber()) {
        output.writeEnum(6, source_);
      }
      if (isEnabled_ != false) {
        output.writeBool(7, isEnabled_);
      }
      if (createdAt_ != 0L) {
        output.writeInt64(8, createdAt_);
      }
      if (updatedAt_ != 0L) {
        output.writeInt64(9, updatedAt_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!integrationId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getIntegrationId());
      }
      if (integrationMessenger_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getIntegrationMessenger());
      }
      if (!serviceProviderAccountId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getServiceProviderAccountId());
      }
      if (!defaultLabelId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getDefaultLabelId());
      }
      if (!serviceId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getServiceId());
      }
      if (source_ != UserProto.ThirdPartySource.UNKNOWN_THIRD_PARTY_SOURCE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, source_);
      }
      if (isEnabled_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, isEnabled_);
      }
      if (createdAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, createdAt_);
      }
      if (updatedAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, updatedAt_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static Integration parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Integration parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Integration parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Integration parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Integration parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Integration parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Integration parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Integration parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Integration parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Integration parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Integration prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code treeleaf.anydone.entities.Integration}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Integration, Builder> implements
        // @@protoc_insertion_point(builder_implements:treeleaf.anydone.entities.Integration)
        IntegrationOrBuilder {
      // Construct using com.treeleaf.anydone.entities.IntegrationProto.Integration.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string integrationId = 1;</code>
       */
      public String getIntegrationId() {
        return instance.getIntegrationId();
      }
      /**
       * <code>optional string integrationId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIntegrationIdBytes() {
        return instance.getIntegrationIdBytes();
      }
      /**
       * <code>optional string integrationId = 1;</code>
       */
      public Builder setIntegrationId(
          String value) {
        copyOnWrite();
        instance.setIntegrationId(value);
        return this;
      }
      /**
       * <code>optional string integrationId = 1;</code>
       */
      public Builder clearIntegrationId() {
        copyOnWrite();
        instance.clearIntegrationId();
        return this;
      }
      /**
       * <code>optional string integrationId = 1;</code>
       */
      public Builder setIntegrationIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIntegrationIdBytes(value);
        return this;
      }

      /**
       * <code>optional .treeleaf.anydone.entities.IntegrationMessenger integrationMessenger = 2;</code>
       */
      public boolean hasIntegrationMessenger() {
        return instance.hasIntegrationMessenger();
      }
      /**
       * <code>optional .treeleaf.anydone.entities.IntegrationMessenger integrationMessenger = 2;</code>
       */
      public IntegrationMessenger getIntegrationMessenger() {
        return instance.getIntegrationMessenger();
      }
      /**
       * <code>optional .treeleaf.anydone.entities.IntegrationMessenger integrationMessenger = 2;</code>
       */
      public Builder setIntegrationMessenger(IntegrationMessenger value) {
        copyOnWrite();
        instance.setIntegrationMessenger(value);
        return this;
        }
      /**
       * <code>optional .treeleaf.anydone.entities.IntegrationMessenger integrationMessenger = 2;</code>
       */
      public Builder setIntegrationMessenger(
          IntegrationMessenger.Builder builderForValue) {
        copyOnWrite();
        instance.setIntegrationMessenger(builderForValue);
        return this;
      }
      /**
       * <code>optional .treeleaf.anydone.entities.IntegrationMessenger integrationMessenger = 2;</code>
       */
      public Builder mergeIntegrationMessenger(IntegrationMessenger value) {
        copyOnWrite();
        instance.mergeIntegrationMessenger(value);
        return this;
      }
      /**
       * <code>optional .treeleaf.anydone.entities.IntegrationMessenger integrationMessenger = 2;</code>
       */
      public Builder clearIntegrationMessenger() {  copyOnWrite();
        instance.clearIntegrationMessenger();
        return this;
      }

      /**
       * <code>optional string serviceProviderAccountId = 3;</code>
       */
      public String getServiceProviderAccountId() {
        return instance.getServiceProviderAccountId();
      }
      /**
       * <code>optional string serviceProviderAccountId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getServiceProviderAccountIdBytes() {
        return instance.getServiceProviderAccountIdBytes();
      }
      /**
       * <code>optional string serviceProviderAccountId = 3;</code>
       */
      public Builder setServiceProviderAccountId(
          String value) {
        copyOnWrite();
        instance.setServiceProviderAccountId(value);
        return this;
      }
      /**
       * <code>optional string serviceProviderAccountId = 3;</code>
       */
      public Builder clearServiceProviderAccountId() {
        copyOnWrite();
        instance.clearServiceProviderAccountId();
        return this;
      }
      /**
       * <code>optional string serviceProviderAccountId = 3;</code>
       */
      public Builder setServiceProviderAccountIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setServiceProviderAccountIdBytes(value);
        return this;
      }

      /**
       * <code>optional string defaultLabelId = 4;</code>
       */
      public String getDefaultLabelId() {
        return instance.getDefaultLabelId();
      }
      /**
       * <code>optional string defaultLabelId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDefaultLabelIdBytes() {
        return instance.getDefaultLabelIdBytes();
      }
      /**
       * <code>optional string defaultLabelId = 4;</code>
       */
      public Builder setDefaultLabelId(
          String value) {
        copyOnWrite();
        instance.setDefaultLabelId(value);
        return this;
      }
      /**
       * <code>optional string defaultLabelId = 4;</code>
       */
      public Builder clearDefaultLabelId() {
        copyOnWrite();
        instance.clearDefaultLabelId();
        return this;
      }
      /**
       * <code>optional string defaultLabelId = 4;</code>
       */
      public Builder setDefaultLabelIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDefaultLabelIdBytes(value);
        return this;
      }

      /**
       * <code>optional string serviceId = 5;</code>
       */
      public String getServiceId() {
        return instance.getServiceId();
      }
      /**
       * <code>optional string serviceId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getServiceIdBytes() {
        return instance.getServiceIdBytes();
      }
      /**
       * <code>optional string serviceId = 5;</code>
       */
      public Builder setServiceId(
          String value) {
        copyOnWrite();
        instance.setServiceId(value);
        return this;
      }
      /**
       * <code>optional string serviceId = 5;</code>
       */
      public Builder clearServiceId() {
        copyOnWrite();
        instance.clearServiceId();
        return this;
      }
      /**
       * <code>optional string serviceId = 5;</code>
       */
      public Builder setServiceIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setServiceIdBytes(value);
        return this;
      }

      /**
       * <code>optional .treeleaf.anydone.entities.ThirdPartySource source = 6;</code>
       */
      public int getSourceValue() {
        return instance.getSourceValue();
      }
      /**
       * <code>optional .treeleaf.anydone.entities.ThirdPartySource source = 6;</code>
       */
      public Builder setSourceValue(int value) {
        copyOnWrite();
        instance.setSourceValue(value);
        return this;
      }
      /**
       * <code>optional .treeleaf.anydone.entities.ThirdPartySource source = 6;</code>
       */
      public UserProto.ThirdPartySource getSource() {
        return instance.getSource();
      }
      /**
       * <code>optional .treeleaf.anydone.entities.ThirdPartySource source = 6;</code>
       */
      public Builder setSource(UserProto.ThirdPartySource value) {
        copyOnWrite();
        instance.setSource(value);
        return this;
      }
      /**
       * <code>optional .treeleaf.anydone.entities.ThirdPartySource source = 6;</code>
       */
      public Builder clearSource() {
        copyOnWrite();
        instance.clearSource();
        return this;
      }

      /**
       * <code>optional bool isEnabled = 7;</code>
       */
      public boolean getIsEnabled() {
        return instance.getIsEnabled();
      }
      /**
       * <code>optional bool isEnabled = 7;</code>
       */
      public Builder setIsEnabled(boolean value) {
        copyOnWrite();
        instance.setIsEnabled(value);
        return this;
      }
      /**
       * <code>optional bool isEnabled = 7;</code>
       */
      public Builder clearIsEnabled() {
        copyOnWrite();
        instance.clearIsEnabled();
        return this;
      }

      /**
       * <code>optional int64 createdAt = 8;</code>
       */
      public long getCreatedAt() {
        return instance.getCreatedAt();
      }
      /**
       * <code>optional int64 createdAt = 8;</code>
       */
      public Builder setCreatedAt(long value) {
        copyOnWrite();
        instance.setCreatedAt(value);
        return this;
      }
      /**
       * <code>optional int64 createdAt = 8;</code>
       */
      public Builder clearCreatedAt() {
        copyOnWrite();
        instance.clearCreatedAt();
        return this;
      }

      /**
       * <code>optional int64 updatedAt = 9;</code>
       */
      public long getUpdatedAt() {
        return instance.getUpdatedAt();
      }
      /**
       * <code>optional int64 updatedAt = 9;</code>
       */
      public Builder setUpdatedAt(long value) {
        copyOnWrite();
        instance.setUpdatedAt(value);
        return this;
      }
      /**
       * <code>optional int64 updatedAt = 9;</code>
       */
      public Builder clearUpdatedAt() {
        copyOnWrite();
        instance.clearUpdatedAt();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:treeleaf.anydone.entities.Integration)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Integration();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          Integration other = (Integration) arg1;
          integrationId_ = visitor.visitString(!integrationId_.isEmpty(), integrationId_,
              !other.integrationId_.isEmpty(), other.integrationId_);
          integrationMessenger_ = visitor.visitMessage(integrationMessenger_, other.integrationMessenger_);
          serviceProviderAccountId_ = visitor.visitString(!serviceProviderAccountId_.isEmpty(), serviceProviderAccountId_,
              !other.serviceProviderAccountId_.isEmpty(), other.serviceProviderAccountId_);
          defaultLabelId_ = visitor.visitString(!defaultLabelId_.isEmpty(), defaultLabelId_,
              !other.defaultLabelId_.isEmpty(), other.defaultLabelId_);
          serviceId_ = visitor.visitString(!serviceId_.isEmpty(), serviceId_,
              !other.serviceId_.isEmpty(), other.serviceId_);
          source_ = visitor.visitInt(source_ != 0, source_,    other.source_ != 0, other.source_);
          isEnabled_ = visitor.visitBoolean(isEnabled_ != false, isEnabled_,
              other.isEnabled_ != false, other.isEnabled_);
          createdAt_ = visitor.visitLong(createdAt_ != 0L, createdAt_,
              other.createdAt_ != 0L, other.createdAt_);
          updatedAt_ = visitor.visitLong(updatedAt_ != 0L, updatedAt_,
              other.updatedAt_ != 0L, other.updatedAt_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  integrationId_ = s;
                  break;
                }
                case 18: {
                  IntegrationMessenger.Builder subBuilder = null;
                  if (integrationMessenger_ != null) {
                    subBuilder = integrationMessenger_.toBuilder();
                  }
                  integrationMessenger_ = input.readMessage(IntegrationMessenger.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(integrationMessenger_);
                    integrationMessenger_ = subBuilder.buildPartial();
                  }

                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  serviceProviderAccountId_ = s;
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();

                  defaultLabelId_ = s;
                  break;
                }
                case 42: {
                  String s = input.readStringRequireUtf8();

                  serviceId_ = s;
                  break;
                }
                case 48: {
                  int rawValue = input.readEnum();

                  source_ = rawValue;
                  break;
                }
                case 56: {

                  isEnabled_ = input.readBool();
                  break;
                }
                case 64: {

                  createdAt_ = input.readInt64();
                  break;
                }
                case 72: {

                  updatedAt_ = input.readInt64();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (Integration.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:treeleaf.anydone.entities.Integration)
    private static final Integration DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Integration();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static Integration getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Integration> PARSER;

    public static com.google.protobuf.Parser<Integration> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface IntegrationMessengerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:treeleaf.anydone.entities.IntegrationMessenger)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string integrationMessengerId = 1;</code>
     */
    String getIntegrationMessengerId();
    /**
     * <code>optional string integrationMessengerId = 1;</code>
     */
    com.google.protobuf.ByteString
        getIntegrationMessengerIdBytes();

    /**
     * <code>optional string verifyToken = 2;</code>
     */
    String getVerifyToken();
    /**
     * <code>optional string verifyToken = 2;</code>
     */
    com.google.protobuf.ByteString
        getVerifyTokenBytes();

    /**
     * <code>optional string pageAccessToken = 3;</code>
     */
    String getPageAccessToken();
    /**
     * <code>optional string pageAccessToken = 3;</code>
     */
    com.google.protobuf.ByteString
        getPageAccessTokenBytes();

    /**
     * <code>optional string integrationId = 4;</code>
     */
    String getIntegrationId();
    /**
     * <code>optional string integrationId = 4;</code>
     */
    com.google.protobuf.ByteString
        getIntegrationIdBytes();

    /**
     * <code>optional int64 createdAt = 5;</code>
     */
    long getCreatedAt();

    /**
     * <code>optional int64 updatedAt = 6;</code>
     */
    long getUpdatedAt();
  }
  /**
   * Protobuf type {@code treeleaf.anydone.entities.IntegrationMessenger}
   */
  public  static final class IntegrationMessenger extends
      com.google.protobuf.GeneratedMessageLite<
          IntegrationMessenger, IntegrationMessenger.Builder> implements
      // @@protoc_insertion_point(message_implements:treeleaf.anydone.entities.IntegrationMessenger)
      IntegrationMessengerOrBuilder {
    private IntegrationMessenger() {
      integrationMessengerId_ = "";
      verifyToken_ = "";
      pageAccessToken_ = "";
      integrationId_ = "";
    }
    public static final int INTEGRATIONMESSENGERID_FIELD_NUMBER = 1;
    private String integrationMessengerId_;
    /**
     * <code>optional string integrationMessengerId = 1;</code>
     */
    public String getIntegrationMessengerId() {
      return integrationMessengerId_;
    }
    /**
     * <code>optional string integrationMessengerId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIntegrationMessengerIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(integrationMessengerId_);
    }
    /**
     * <code>optional string integrationMessengerId = 1;</code>
     */
    private void setIntegrationMessengerId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      integrationMessengerId_ = value;
    }
    /**
     * <code>optional string integrationMessengerId = 1;</code>
     */
    private void clearIntegrationMessengerId() {
      
      integrationMessengerId_ = getDefaultInstance().getIntegrationMessengerId();
    }
    /**
     * <code>optional string integrationMessengerId = 1;</code>
     */
    private void setIntegrationMessengerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      integrationMessengerId_ = value.toStringUtf8();
    }

    public static final int VERIFYTOKEN_FIELD_NUMBER = 2;
    private String verifyToken_;
    /**
     * <code>optional string verifyToken = 2;</code>
     */
    public String getVerifyToken() {
      return verifyToken_;
    }
    /**
     * <code>optional string verifyToken = 2;</code>
     */
    public com.google.protobuf.ByteString
        getVerifyTokenBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(verifyToken_);
    }
    /**
     * <code>optional string verifyToken = 2;</code>
     */
    private void setVerifyToken(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      verifyToken_ = value;
    }
    /**
     * <code>optional string verifyToken = 2;</code>
     */
    private void clearVerifyToken() {
      
      verifyToken_ = getDefaultInstance().getVerifyToken();
    }
    /**
     * <code>optional string verifyToken = 2;</code>
     */
    private void setVerifyTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      verifyToken_ = value.toStringUtf8();
    }

    public static final int PAGEACCESSTOKEN_FIELD_NUMBER = 3;
    private String pageAccessToken_;
    /**
     * <code>optional string pageAccessToken = 3;</code>
     */
    public String getPageAccessToken() {
      return pageAccessToken_;
    }
    /**
     * <code>optional string pageAccessToken = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPageAccessTokenBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(pageAccessToken_);
    }
    /**
     * <code>optional string pageAccessToken = 3;</code>
     */
    private void setPageAccessToken(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pageAccessToken_ = value;
    }
    /**
     * <code>optional string pageAccessToken = 3;</code>
     */
    private void clearPageAccessToken() {
      
      pageAccessToken_ = getDefaultInstance().getPageAccessToken();
    }
    /**
     * <code>optional string pageAccessToken = 3;</code>
     */
    private void setPageAccessTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pageAccessToken_ = value.toStringUtf8();
    }

    public static final int INTEGRATIONID_FIELD_NUMBER = 4;
    private String integrationId_;
    /**
     * <code>optional string integrationId = 4;</code>
     */
    public String getIntegrationId() {
      return integrationId_;
    }
    /**
     * <code>optional string integrationId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIntegrationIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(integrationId_);
    }
    /**
     * <code>optional string integrationId = 4;</code>
     */
    private void setIntegrationId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      integrationId_ = value;
    }
    /**
     * <code>optional string integrationId = 4;</code>
     */
    private void clearIntegrationId() {
      
      integrationId_ = getDefaultInstance().getIntegrationId();
    }
    /**
     * <code>optional string integrationId = 4;</code>
     */
    private void setIntegrationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      integrationId_ = value.toStringUtf8();
    }

    public static final int CREATEDAT_FIELD_NUMBER = 5;
    private long createdAt_;
    /**
     * <code>optional int64 createdAt = 5;</code>
     */
    public long getCreatedAt() {
      return createdAt_;
    }
    /**
     * <code>optional int64 createdAt = 5;</code>
     */
    private void setCreatedAt(long value) {
      
      createdAt_ = value;
    }
    /**
     * <code>optional int64 createdAt = 5;</code>
     */
    private void clearCreatedAt() {
      
      createdAt_ = 0L;
    }

    public static final int UPDATEDAT_FIELD_NUMBER = 6;
    private long updatedAt_;
    /**
     * <code>optional int64 updatedAt = 6;</code>
     */
    public long getUpdatedAt() {
      return updatedAt_;
    }
    /**
     * <code>optional int64 updatedAt = 6;</code>
     */
    private void setUpdatedAt(long value) {
      
      updatedAt_ = value;
    }
    /**
     * <code>optional int64 updatedAt = 6;</code>
     */
    private void clearUpdatedAt() {
      
      updatedAt_ = 0L;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!integrationMessengerId_.isEmpty()) {
        output.writeString(1, getIntegrationMessengerId());
      }
      if (!verifyToken_.isEmpty()) {
        output.writeString(2, getVerifyToken());
      }
      if (!pageAccessToken_.isEmpty()) {
        output.writeString(3, getPageAccessToken());
      }
      if (!integrationId_.isEmpty()) {
        output.writeString(4, getIntegrationId());
      }
      if (createdAt_ != 0L) {
        output.writeInt64(5, createdAt_);
      }
      if (updatedAt_ != 0L) {
        output.writeInt64(6, updatedAt_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!integrationMessengerId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getIntegrationMessengerId());
      }
      if (!verifyToken_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getVerifyToken());
      }
      if (!pageAccessToken_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getPageAccessToken());
      }
      if (!integrationId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getIntegrationId());
      }
      if (createdAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, createdAt_);
      }
      if (updatedAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, updatedAt_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static IntegrationMessenger parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static IntegrationMessenger parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static IntegrationMessenger parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static IntegrationMessenger parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static IntegrationMessenger parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static IntegrationMessenger parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static IntegrationMessenger parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static IntegrationMessenger parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static IntegrationMessenger parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static IntegrationMessenger parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(IntegrationMessenger prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code treeleaf.anydone.entities.IntegrationMessenger}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          IntegrationMessenger, Builder> implements
        // @@protoc_insertion_point(builder_implements:treeleaf.anydone.entities.IntegrationMessenger)
        IntegrationMessengerOrBuilder {
      // Construct using com.treeleaf.anydone.entities.IntegrationProto.IntegrationMessenger.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string integrationMessengerId = 1;</code>
       */
      public String getIntegrationMessengerId() {
        return instance.getIntegrationMessengerId();
      }
      /**
       * <code>optional string integrationMessengerId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIntegrationMessengerIdBytes() {
        return instance.getIntegrationMessengerIdBytes();
      }
      /**
       * <code>optional string integrationMessengerId = 1;</code>
       */
      public Builder setIntegrationMessengerId(
          String value) {
        copyOnWrite();
        instance.setIntegrationMessengerId(value);
        return this;
      }
      /**
       * <code>optional string integrationMessengerId = 1;</code>
       */
      public Builder clearIntegrationMessengerId() {
        copyOnWrite();
        instance.clearIntegrationMessengerId();
        return this;
      }
      /**
       * <code>optional string integrationMessengerId = 1;</code>
       */
      public Builder setIntegrationMessengerIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIntegrationMessengerIdBytes(value);
        return this;
      }

      /**
       * <code>optional string verifyToken = 2;</code>
       */
      public String getVerifyToken() {
        return instance.getVerifyToken();
      }
      /**
       * <code>optional string verifyToken = 2;</code>
       */
      public com.google.protobuf.ByteString
          getVerifyTokenBytes() {
        return instance.getVerifyTokenBytes();
      }
      /**
       * <code>optional string verifyToken = 2;</code>
       */
      public Builder setVerifyToken(
          String value) {
        copyOnWrite();
        instance.setVerifyToken(value);
        return this;
      }
      /**
       * <code>optional string verifyToken = 2;</code>
       */
      public Builder clearVerifyToken() {
        copyOnWrite();
        instance.clearVerifyToken();
        return this;
      }
      /**
       * <code>optional string verifyToken = 2;</code>
       */
      public Builder setVerifyTokenBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setVerifyTokenBytes(value);
        return this;
      }

      /**
       * <code>optional string pageAccessToken = 3;</code>
       */
      public String getPageAccessToken() {
        return instance.getPageAccessToken();
      }
      /**
       * <code>optional string pageAccessToken = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPageAccessTokenBytes() {
        return instance.getPageAccessTokenBytes();
      }
      /**
       * <code>optional string pageAccessToken = 3;</code>
       */
      public Builder setPageAccessToken(
          String value) {
        copyOnWrite();
        instance.setPageAccessToken(value);
        return this;
      }
      /**
       * <code>optional string pageAccessToken = 3;</code>
       */
      public Builder clearPageAccessToken() {
        copyOnWrite();
        instance.clearPageAccessToken();
        return this;
      }
      /**
       * <code>optional string pageAccessToken = 3;</code>
       */
      public Builder setPageAccessTokenBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPageAccessTokenBytes(value);
        return this;
      }

      /**
       * <code>optional string integrationId = 4;</code>
       */
      public String getIntegrationId() {
        return instance.getIntegrationId();
      }
      /**
       * <code>optional string integrationId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getIntegrationIdBytes() {
        return instance.getIntegrationIdBytes();
      }
      /**
       * <code>optional string integrationId = 4;</code>
       */
      public Builder setIntegrationId(
          String value) {
        copyOnWrite();
        instance.setIntegrationId(value);
        return this;
      }
      /**
       * <code>optional string integrationId = 4;</code>
       */
      public Builder clearIntegrationId() {
        copyOnWrite();
        instance.clearIntegrationId();
        return this;
      }
      /**
       * <code>optional string integrationId = 4;</code>
       */
      public Builder setIntegrationIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIntegrationIdBytes(value);
        return this;
      }

      /**
       * <code>optional int64 createdAt = 5;</code>
       */
      public long getCreatedAt() {
        return instance.getCreatedAt();
      }
      /**
       * <code>optional int64 createdAt = 5;</code>
       */
      public Builder setCreatedAt(long value) {
        copyOnWrite();
        instance.setCreatedAt(value);
        return this;
      }
      /**
       * <code>optional int64 createdAt = 5;</code>
       */
      public Builder clearCreatedAt() {
        copyOnWrite();
        instance.clearCreatedAt();
        return this;
      }

      /**
       * <code>optional int64 updatedAt = 6;</code>
       */
      public long getUpdatedAt() {
        return instance.getUpdatedAt();
      }
      /**
       * <code>optional int64 updatedAt = 6;</code>
       */
      public Builder setUpdatedAt(long value) {
        copyOnWrite();
        instance.setUpdatedAt(value);
        return this;
      }
      /**
       * <code>optional int64 updatedAt = 6;</code>
       */
      public Builder clearUpdatedAt() {
        copyOnWrite();
        instance.clearUpdatedAt();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:treeleaf.anydone.entities.IntegrationMessenger)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new IntegrationMessenger();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          IntegrationMessenger other = (IntegrationMessenger) arg1;
          integrationMessengerId_ = visitor.visitString(!integrationMessengerId_.isEmpty(), integrationMessengerId_,
              !other.integrationMessengerId_.isEmpty(), other.integrationMessengerId_);
          verifyToken_ = visitor.visitString(!verifyToken_.isEmpty(), verifyToken_,
              !other.verifyToken_.isEmpty(), other.verifyToken_);
          pageAccessToken_ = visitor.visitString(!pageAccessToken_.isEmpty(), pageAccessToken_,
              !other.pageAccessToken_.isEmpty(), other.pageAccessToken_);
          integrationId_ = visitor.visitString(!integrationId_.isEmpty(), integrationId_,
              !other.integrationId_.isEmpty(), other.integrationId_);
          createdAt_ = visitor.visitLong(createdAt_ != 0L, createdAt_,
              other.createdAt_ != 0L, other.createdAt_);
          updatedAt_ = visitor.visitLong(updatedAt_ != 0L, updatedAt_,
              other.updatedAt_ != 0L, other.updatedAt_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  integrationMessengerId_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  verifyToken_ = s;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  pageAccessToken_ = s;
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();

                  integrationId_ = s;
                  break;
                }
                case 40: {

                  createdAt_ = input.readInt64();
                  break;
                }
                case 48: {

                  updatedAt_ = input.readInt64();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (IntegrationMessenger.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:treeleaf.anydone.entities.IntegrationMessenger)
    private static final IntegrationMessenger DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new IntegrationMessenger();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static IntegrationMessenger getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<IntegrationMessenger> PARSER;

    public static com.google.protobuf.Parser<IntegrationMessenger> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
