// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nlp.proto

package com.treeleaf.anydone.entities;

public final class NLPProto {
  private NLPProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface NLPInputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:treeleaf.anydone.entities.NLPInput)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string text = 1;</code>
     */
    String getText();
    /**
     * <code>optional string text = 1;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();

    /**
     * <code>optional string timezone = 2;</code>
     */
    String getTimezone();
    /**
     * <code>optional string timezone = 2;</code>
     */
    com.google.protobuf.ByteString
        getTimezoneBytes();

    /**
     * <code>optional string language = 3;</code>
     */
    String getLanguage();
    /**
     * <code>optional string language = 3;</code>
     */
    com.google.protobuf.ByteString
        getLanguageBytes();

    /**
     * <code>optional string requestId = 4;</code>
     */
    String getRequestId();
    /**
     * <code>optional string requestId = 4;</code>
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();
  }
  /**
   * Protobuf type {@code treeleaf.anydone.entities.NLPInput}
   */
  public  static final class NLPInput extends
      com.google.protobuf.GeneratedMessageLite<
          NLPInput, NLPInput.Builder> implements
      // @@protoc_insertion_point(message_implements:treeleaf.anydone.entities.NLPInput)
      NLPInputOrBuilder {
    private NLPInput() {
      text_ = "";
      timezone_ = "";
      language_ = "";
      requestId_ = "";
    }
    public static final int TEXT_FIELD_NUMBER = 1;
    private String text_;
    /**
     * <code>optional string text = 1;</code>
     */
    public String getText() {
      return text_;
    }
    /**
     * <code>optional string text = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(text_);
    }
    /**
     * <code>optional string text = 1;</code>
     */
    private void setText(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      text_ = value;
    }
    /**
     * <code>optional string text = 1;</code>
     */
    private void clearText() {
      
      text_ = getDefaultInstance().getText();
    }
    /**
     * <code>optional string text = 1;</code>
     */
    private void setTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      text_ = value.toStringUtf8();
    }

    public static final int TIMEZONE_FIELD_NUMBER = 2;
    private String timezone_;
    /**
     * <code>optional string timezone = 2;</code>
     */
    public String getTimezone() {
      return timezone_;
    }
    /**
     * <code>optional string timezone = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTimezoneBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(timezone_);
    }
    /**
     * <code>optional string timezone = 2;</code>
     */
    private void setTimezone(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      timezone_ = value;
    }
    /**
     * <code>optional string timezone = 2;</code>
     */
    private void clearTimezone() {
      
      timezone_ = getDefaultInstance().getTimezone();
    }
    /**
     * <code>optional string timezone = 2;</code>
     */
    private void setTimezoneBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      timezone_ = value.toStringUtf8();
    }

    public static final int LANGUAGE_FIELD_NUMBER = 3;
    private String language_;
    /**
     * <code>optional string language = 3;</code>
     */
    public String getLanguage() {
      return language_;
    }
    /**
     * <code>optional string language = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(language_);
    }
    /**
     * <code>optional string language = 3;</code>
     */
    private void setLanguage(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      language_ = value;
    }
    /**
     * <code>optional string language = 3;</code>
     */
    private void clearLanguage() {
      
      language_ = getDefaultInstance().getLanguage();
    }
    /**
     * <code>optional string language = 3;</code>
     */
    private void setLanguageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      language_ = value.toStringUtf8();
    }

    public static final int REQUESTID_FIELD_NUMBER = 4;
    private String requestId_;
    /**
     * <code>optional string requestId = 4;</code>
     */
    public String getRequestId() {
      return requestId_;
    }
    /**
     * <code>optional string requestId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(requestId_);
    }
    /**
     * <code>optional string requestId = 4;</code>
     */
    private void setRequestId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      requestId_ = value;
    }
    /**
     * <code>optional string requestId = 4;</code>
     */
    private void clearRequestId() {
      
      requestId_ = getDefaultInstance().getRequestId();
    }
    /**
     * <code>optional string requestId = 4;</code>
     */
    private void setRequestIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      requestId_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!text_.isEmpty()) {
        output.writeString(1, getText());
      }
      if (!timezone_.isEmpty()) {
        output.writeString(2, getTimezone());
      }
      if (!language_.isEmpty()) {
        output.writeString(3, getLanguage());
      }
      if (!requestId_.isEmpty()) {
        output.writeString(4, getRequestId());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!text_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getText());
      }
      if (!timezone_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getTimezone());
      }
      if (!language_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getLanguage());
      }
      if (!requestId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getRequestId());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static NLPInput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static NLPInput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static NLPInput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static NLPInput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static NLPInput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static NLPInput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static NLPInput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static NLPInput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static NLPInput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static NLPInput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(NLPInput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code treeleaf.anydone.entities.NLPInput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          NLPInput, Builder> implements
        // @@protoc_insertion_point(builder_implements:treeleaf.anydone.entities.NLPInput)
        NLPInputOrBuilder {
      // Construct using com.treeleaf.anydone.entities.NLPProto.NLPInput.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string text = 1;</code>
       */
      public String getText() {
        return instance.getText();
      }
      /**
       * <code>optional string text = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        return instance.getTextBytes();
      }
      /**
       * <code>optional string text = 1;</code>
       */
      public Builder setText(
          String value) {
        copyOnWrite();
        instance.setText(value);
        return this;
      }
      /**
       * <code>optional string text = 1;</code>
       */
      public Builder clearText() {
        copyOnWrite();
        instance.clearText();
        return this;
      }
      /**
       * <code>optional string text = 1;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTextBytes(value);
        return this;
      }

      /**
       * <code>optional string timezone = 2;</code>
       */
      public String getTimezone() {
        return instance.getTimezone();
      }
      /**
       * <code>optional string timezone = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTimezoneBytes() {
        return instance.getTimezoneBytes();
      }
      /**
       * <code>optional string timezone = 2;</code>
       */
      public Builder setTimezone(
          String value) {
        copyOnWrite();
        instance.setTimezone(value);
        return this;
      }
      /**
       * <code>optional string timezone = 2;</code>
       */
      public Builder clearTimezone() {
        copyOnWrite();
        instance.clearTimezone();
        return this;
      }
      /**
       * <code>optional string timezone = 2;</code>
       */
      public Builder setTimezoneBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTimezoneBytes(value);
        return this;
      }

      /**
       * <code>optional string language = 3;</code>
       */
      public String getLanguage() {
        return instance.getLanguage();
      }
      /**
       * <code>optional string language = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLanguageBytes() {
        return instance.getLanguageBytes();
      }
      /**
       * <code>optional string language = 3;</code>
       */
      public Builder setLanguage(
          String value) {
        copyOnWrite();
        instance.setLanguage(value);
        return this;
      }
      /**
       * <code>optional string language = 3;</code>
       */
      public Builder clearLanguage() {
        copyOnWrite();
        instance.clearLanguage();
        return this;
      }
      /**
       * <code>optional string language = 3;</code>
       */
      public Builder setLanguageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLanguageBytes(value);
        return this;
      }

      /**
       * <code>optional string requestId = 4;</code>
       */
      public String getRequestId() {
        return instance.getRequestId();
      }
      /**
       * <code>optional string requestId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        return instance.getRequestIdBytes();
      }
      /**
       * <code>optional string requestId = 4;</code>
       */
      public Builder setRequestId(
          String value) {
        copyOnWrite();
        instance.setRequestId(value);
        return this;
      }
      /**
       * <code>optional string requestId = 4;</code>
       */
      public Builder clearRequestId() {
        copyOnWrite();
        instance.clearRequestId();
        return this;
      }
      /**
       * <code>optional string requestId = 4;</code>
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setRequestIdBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:treeleaf.anydone.entities.NLPInput)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new NLPInput();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          NLPInput other = (NLPInput) arg1;
          text_ = visitor.visitString(!text_.isEmpty(), text_,
              !other.text_.isEmpty(), other.text_);
          timezone_ = visitor.visitString(!timezone_.isEmpty(), timezone_,
              !other.timezone_.isEmpty(), other.timezone_);
          language_ = visitor.visitString(!language_.isEmpty(), language_,
              !other.language_.isEmpty(), other.language_);
          requestId_ = visitor.visitString(!requestId_.isEmpty(), requestId_,
              !other.requestId_.isEmpty(), other.requestId_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  text_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  timezone_ = s;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  language_ = s;
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();

                  requestId_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (NLPInput.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:treeleaf.anydone.entities.NLPInput)
    private static final NLPInput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NLPInput();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static NLPInput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<NLPInput> PARSER;

    public static com.google.protobuf.Parser<NLPInput> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface EntityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:treeleaf.anydone.entities.Entity)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 start = 2;</code>
     */
    int getStart();

    /**
     * <code>optional int32 end = 3;</code>
     */
    int getEnd();

    /**
     * <code>optional string extractor = 4;</code>
     */
    String getExtractor();
    /**
     * <code>optional string extractor = 4;</code>
     */
    com.google.protobuf.ByteString
        getExtractorBytes();

    /**
     * <code>optional string value = 5;</code>
     */
    String getValue();
    /**
     * <code>optional string value = 5;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();

    /**
     * <code>optional string absoluteTime = 6;</code>
     */
    String getAbsoluteTime();
    /**
     * <code>optional string absoluteTime = 6;</code>
     */
    com.google.protobuf.ByteString
        getAbsoluteTimeBytes();
  }
  /**
   * Protobuf type {@code treeleaf.anydone.entities.Entity}
   */
  public  static final class Entity extends
      com.google.protobuf.GeneratedMessageLite<
          Entity, Entity.Builder> implements
      // @@protoc_insertion_point(message_implements:treeleaf.anydone.entities.Entity)
      EntityOrBuilder {
    private Entity() {
      name_ = "";
      extractor_ = "";
      value_ = "";
      absoluteTime_ = "";
    }
    public static final int NAME_FIELD_NUMBER = 1;
    private String name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public String getName() {
      return name_;
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>optional string name = 1;</code>
     */
    private void setName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
    }
    /**
     * <code>optional string name = 1;</code>
     */
    private void clearName() {
      
      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>optional string name = 1;</code>
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value.toStringUtf8();
    }

    public static final int START_FIELD_NUMBER = 2;
    private int start_;
    /**
     * <code>optional int32 start = 2;</code>
     */
    public int getStart() {
      return start_;
    }
    /**
     * <code>optional int32 start = 2;</code>
     */
    private void setStart(int value) {
      
      start_ = value;
    }
    /**
     * <code>optional int32 start = 2;</code>
     */
    private void clearStart() {
      
      start_ = 0;
    }

    public static final int END_FIELD_NUMBER = 3;
    private int end_;
    /**
     * <code>optional int32 end = 3;</code>
     */
    public int getEnd() {
      return end_;
    }
    /**
     * <code>optional int32 end = 3;</code>
     */
    private void setEnd(int value) {
      
      end_ = value;
    }
    /**
     * <code>optional int32 end = 3;</code>
     */
    private void clearEnd() {
      
      end_ = 0;
    }

    public static final int EXTRACTOR_FIELD_NUMBER = 4;
    private String extractor_;
    /**
     * <code>optional string extractor = 4;</code>
     */
    public String getExtractor() {
      return extractor_;
    }
    /**
     * <code>optional string extractor = 4;</code>
     */
    public com.google.protobuf.ByteString
        getExtractorBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(extractor_);
    }
    /**
     * <code>optional string extractor = 4;</code>
     */
    private void setExtractor(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      extractor_ = value;
    }
    /**
     * <code>optional string extractor = 4;</code>
     */
    private void clearExtractor() {
      
      extractor_ = getDefaultInstance().getExtractor();
    }
    /**
     * <code>optional string extractor = 4;</code>
     */
    private void setExtractorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      extractor_ = value.toStringUtf8();
    }

    public static final int VALUE_FIELD_NUMBER = 5;
    private String value_;
    /**
     * <code>optional string value = 5;</code>
     */
    public String getValue() {
      return value_;
    }
    /**
     * <code>optional string value = 5;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(value_);
    }
    /**
     * <code>optional string value = 5;</code>
     */
    private void setValue(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      value_ = value;
    }
    /**
     * <code>optional string value = 5;</code>
     */
    private void clearValue() {
      
      value_ = getDefaultInstance().getValue();
    }
    /**
     * <code>optional string value = 5;</code>
     */
    private void setValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      value_ = value.toStringUtf8();
    }

    public static final int ABSOLUTETIME_FIELD_NUMBER = 6;
    private String absoluteTime_;
    /**
     * <code>optional string absoluteTime = 6;</code>
     */
    public String getAbsoluteTime() {
      return absoluteTime_;
    }
    /**
     * <code>optional string absoluteTime = 6;</code>
     */
    public com.google.protobuf.ByteString
        getAbsoluteTimeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(absoluteTime_);
    }
    /**
     * <code>optional string absoluteTime = 6;</code>
     */
    private void setAbsoluteTime(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      absoluteTime_ = value;
    }
    /**
     * <code>optional string absoluteTime = 6;</code>
     */
    private void clearAbsoluteTime() {
      
      absoluteTime_ = getDefaultInstance().getAbsoluteTime();
    }
    /**
     * <code>optional string absoluteTime = 6;</code>
     */
    private void setAbsoluteTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      absoluteTime_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!name_.isEmpty()) {
        output.writeString(1, getName());
      }
      if (start_ != 0) {
        output.writeInt32(2, start_);
      }
      if (end_ != 0) {
        output.writeInt32(3, end_);
      }
      if (!extractor_.isEmpty()) {
        output.writeString(4, getExtractor());
      }
      if (!value_.isEmpty()) {
        output.writeString(5, getValue());
      }
      if (!absoluteTime_.isEmpty()) {
        output.writeString(6, getAbsoluteTime());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!name_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getName());
      }
      if (start_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, start_);
      }
      if (end_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, end_);
      }
      if (!extractor_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getExtractor());
      }
      if (!value_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getValue());
      }
      if (!absoluteTime_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getAbsoluteTime());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static Entity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Entity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Entity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Entity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Entity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Entity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Entity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Entity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Entity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Entity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Entity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code treeleaf.anydone.entities.Entity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Entity, Builder> implements
        // @@protoc_insertion_point(builder_implements:treeleaf.anydone.entities.Entity)
        EntityOrBuilder {
      // Construct using com.treeleaf.anydone.entities.NLPProto.Entity.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string name = 1;</code>
       */
      public String getName() {
        return instance.getName();
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <code>optional int32 start = 2;</code>
       */
      public int getStart() {
        return instance.getStart();
      }
      /**
       * <code>optional int32 start = 2;</code>
       */
      public Builder setStart(int value) {
        copyOnWrite();
        instance.setStart(value);
        return this;
      }
      /**
       * <code>optional int32 start = 2;</code>
       */
      public Builder clearStart() {
        copyOnWrite();
        instance.clearStart();
        return this;
      }

      /**
       * <code>optional int32 end = 3;</code>
       */
      public int getEnd() {
        return instance.getEnd();
      }
      /**
       * <code>optional int32 end = 3;</code>
       */
      public Builder setEnd(int value) {
        copyOnWrite();
        instance.setEnd(value);
        return this;
      }
      /**
       * <code>optional int32 end = 3;</code>
       */
      public Builder clearEnd() {
        copyOnWrite();
        instance.clearEnd();
        return this;
      }

      /**
       * <code>optional string extractor = 4;</code>
       */
      public String getExtractor() {
        return instance.getExtractor();
      }
      /**
       * <code>optional string extractor = 4;</code>
       */
      public com.google.protobuf.ByteString
          getExtractorBytes() {
        return instance.getExtractorBytes();
      }
      /**
       * <code>optional string extractor = 4;</code>
       */
      public Builder setExtractor(
          String value) {
        copyOnWrite();
        instance.setExtractor(value);
        return this;
      }
      /**
       * <code>optional string extractor = 4;</code>
       */
      public Builder clearExtractor() {
        copyOnWrite();
        instance.clearExtractor();
        return this;
      }
      /**
       * <code>optional string extractor = 4;</code>
       */
      public Builder setExtractorBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setExtractorBytes(value);
        return this;
      }

      /**
       * <code>optional string value = 5;</code>
       */
      public String getValue() {
        return instance.getValue();
      }
      /**
       * <code>optional string value = 5;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        return instance.getValueBytes();
      }
      /**
       * <code>optional string value = 5;</code>
       */
      public Builder setValue(
          String value) {
        copyOnWrite();
        instance.setValue(value);
        return this;
      }
      /**
       * <code>optional string value = 5;</code>
       */
      public Builder clearValue() {
        copyOnWrite();
        instance.clearValue();
        return this;
      }
      /**
       * <code>optional string value = 5;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setValueBytes(value);
        return this;
      }

      /**
       * <code>optional string absoluteTime = 6;</code>
       */
      public String getAbsoluteTime() {
        return instance.getAbsoluteTime();
      }
      /**
       * <code>optional string absoluteTime = 6;</code>
       */
      public com.google.protobuf.ByteString
          getAbsoluteTimeBytes() {
        return instance.getAbsoluteTimeBytes();
      }
      /**
       * <code>optional string absoluteTime = 6;</code>
       */
      public Builder setAbsoluteTime(
          String value) {
        copyOnWrite();
        instance.setAbsoluteTime(value);
        return this;
      }
      /**
       * <code>optional string absoluteTime = 6;</code>
       */
      public Builder clearAbsoluteTime() {
        copyOnWrite();
        instance.clearAbsoluteTime();
        return this;
      }
      /**
       * <code>optional string absoluteTime = 6;</code>
       */
      public Builder setAbsoluteTimeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAbsoluteTimeBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:treeleaf.anydone.entities.Entity)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Entity();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          Entity other = (Entity) arg1;
          name_ = visitor.visitString(!name_.isEmpty(), name_,
              !other.name_.isEmpty(), other.name_);
          start_ = visitor.visitInt(start_ != 0, start_,
              other.start_ != 0, other.start_);
          end_ = visitor.visitInt(end_ != 0, end_,
              other.end_ != 0, other.end_);
          extractor_ = visitor.visitString(!extractor_.isEmpty(), extractor_,
              !other.extractor_.isEmpty(), other.extractor_);
          value_ = visitor.visitString(!value_.isEmpty(), value_,
              !other.value_.isEmpty(), other.value_);
          absoluteTime_ = visitor.visitString(!absoluteTime_.isEmpty(), absoluteTime_,
              !other.absoluteTime_.isEmpty(), other.absoluteTime_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  name_ = s;
                  break;
                }
                case 16: {

                  start_ = input.readInt32();
                  break;
                }
                case 24: {

                  end_ = input.readInt32();
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();

                  extractor_ = s;
                  break;
                }
                case 42: {
                  String s = input.readStringRequireUtf8();

                  value_ = s;
                  break;
                }
                case 50: {
                  String s = input.readStringRequireUtf8();

                  absoluteTime_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (Entity.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:treeleaf.anydone.entities.Entity)
    private static final Entity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Entity();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static Entity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Entity> PARSER;

    public static com.google.protobuf.Parser<Entity> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface NERResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:treeleaf.anydone.entities.NERResult)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
     */
    java.util.List<Entity>
        getEntitiesList();
    /**
     * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
     */
    Entity getEntities(int index);
    /**
     * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
     */
    int getEntitiesCount();
  }
  /**
   * Protobuf type {@code treeleaf.anydone.entities.NERResult}
   */
  public  static final class NERResult extends
      com.google.protobuf.GeneratedMessageLite<
          NERResult, NERResult.Builder> implements
      // @@protoc_insertion_point(message_implements:treeleaf.anydone.entities.NERResult)
      NERResultOrBuilder {
    private NERResult() {
      entities_ = emptyProtobufList();
    }
    public static final int ENTITIES_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<Entity> entities_;
    /**
     * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
     */
    public java.util.List<Entity> getEntitiesList() {
      return entities_;
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
     */
    public java.util.List<? extends EntityOrBuilder>
        getEntitiesOrBuilderList() {
      return entities_;
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
     */
    public int getEntitiesCount() {
      return entities_.size();
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
     */
    public Entity getEntities(int index) {
      return entities_.get(index);
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
     */
    public EntityOrBuilder getEntitiesOrBuilder(
        int index) {
      return entities_.get(index);
    }
    private void ensureEntitiesIsMutable() {
      if (!entities_.isModifiable()) {
        entities_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(entities_);
       }
    }

    /**
     * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
     */
    private void setEntities(
        int index, Entity value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureEntitiesIsMutable();
      entities_.set(index, value);
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
     */
    private void setEntities(
        int index, Entity.Builder builderForValue) {
      ensureEntitiesIsMutable();
      entities_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
     */
    private void addEntities(Entity value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureEntitiesIsMutable();
      entities_.add(value);
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
     */
    private void addEntities(
        int index, Entity value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureEntitiesIsMutable();
      entities_.add(index, value);
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
     */
    private void addEntities(
        Entity.Builder builderForValue) {
      ensureEntitiesIsMutable();
      entities_.add(builderForValue.build());
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
     */
    private void addEntities(
        int index, Entity.Builder builderForValue) {
      ensureEntitiesIsMutable();
      entities_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
     */
    private void addAllEntities(
        Iterable<? extends Entity> values) {
      ensureEntitiesIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, entities_);
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
     */
    private void clearEntities() {
      entities_ = emptyProtobufList();
    }
    /**
     * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
     */
    private void removeEntities(int index) {
      ensureEntitiesIsMutable();
      entities_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < entities_.size(); i++) {
        output.writeMessage(1, entities_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < entities_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, entities_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static NERResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static NERResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static NERResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static NERResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static NERResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static NERResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static NERResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static NERResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static NERResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static NERResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(NERResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code treeleaf.anydone.entities.NERResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          NERResult, Builder> implements
        // @@protoc_insertion_point(builder_implements:treeleaf.anydone.entities.NERResult)
        NERResultOrBuilder {
      // Construct using com.treeleaf.anydone.entities.NLPProto.NERResult.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
       */
      public java.util.List<Entity> getEntitiesList() {
        return java.util.Collections.unmodifiableList(
            instance.getEntitiesList());
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
       */
      public int getEntitiesCount() {
        return instance.getEntitiesCount();
      }/**
       * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
       */
      public Entity getEntities(int index) {
        return instance.getEntities(index);
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
       */
      public Builder setEntities(
          int index, Entity value) {
        copyOnWrite();
        instance.setEntities(index, value);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
       */
      public Builder setEntities(
          int index, Entity.Builder builderForValue) {
        copyOnWrite();
        instance.setEntities(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
       */
      public Builder addEntities(Entity value) {
        copyOnWrite();
        instance.addEntities(value);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
       */
      public Builder addEntities(
          int index, Entity value) {
        copyOnWrite();
        instance.addEntities(index, value);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
       */
      public Builder addEntities(
          Entity.Builder builderForValue) {
        copyOnWrite();
        instance.addEntities(builderForValue);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
       */
      public Builder addEntities(
          int index, Entity.Builder builderForValue) {
        copyOnWrite();
        instance.addEntities(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
       */
      public Builder addAllEntities(
          Iterable<? extends Entity> values) {
        copyOnWrite();
        instance.addAllEntities(values);
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
       */
      public Builder clearEntities() {
        copyOnWrite();
        instance.clearEntities();
        return this;
      }
      /**
       * <code>repeated .treeleaf.anydone.entities.Entity entities = 1;</code>
       */
      public Builder removeEntities(int index) {
        copyOnWrite();
        instance.removeEntities(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:treeleaf.anydone.entities.NERResult)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new NERResult();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          entities_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          NERResult other = (NERResult) arg1;
          entities_= visitor.visitList(entities_, other.entities_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!entities_.isModifiable()) {
                    entities_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(entities_);
                  }
                  entities_.add(
                      input.readMessage(Entity.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (NERResult.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:treeleaf.anydone.entities.NERResult)
    private static final NERResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NERResult();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static NERResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<NERResult> PARSER;

    public static com.google.protobuf.Parser<NERResult> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
